/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from "../runtime";
import useSWR from "swr";
import { SWRConfiguration } from "swr/_internal";

import {
  CreateDropTierDto,
  CreateDropTierDtoFromJSON,
  CreateDropTierDtoToJSON,
  DropSettingsDto,
  DropSettingsDtoFromJSON,
  DropSettingsDtoToJSON,
  DropTierDto,
  DropTierDtoFromJSON,
  DropTierDtoToJSON,
  DroppedItemDto,
  DroppedItemDtoFromJSON,
  DroppedItemDtoToJSON,
  PurchaseWithTradeBalanceDto,
  PurchaseWithTradeBalanceDtoFromJSON,
  PurchaseWithTradeBalanceDtoToJSON,
  TradeOfferDto,
  TradeOfferDtoFromJSON,
  TradeOfferDtoToJSON,
  TradeUserDto,
  TradeUserDtoFromJSON,
  TradeUserDtoToJSON,
  UpdateDropSettingsDto,
  UpdateDropSettingsDtoFromJSON,
  UpdateDropSettingsDtoToJSON,
  UpdateDropTierDto,
  UpdateDropTierDtoFromJSON,
  UpdateDropTierDtoToJSON,
  UpdateTradeLinkDto,
  UpdateTradeLinkDtoFromJSON,
  UpdateTradeLinkDtoToJSON,
} from "../models";

export interface ItemDropControllerCreateDropTierRequest {
  createDropTierDto: CreateDropTierDto;
}

export interface ItemDropControllerDeleteTierRequest {
  id: number;
}

export interface ItemDropControllerDiscardDropRequest {
  id: string;
}

export interface ItemDropControllerPurchaseSubscriptionWithTradeBalanceRequest {
  purchaseWithTradeBalanceDto: PurchaseWithTradeBalanceDto;
}

export interface ItemDropControllerUpdateSettingsRequest {
  updateDropSettingsDto: UpdateDropSettingsDto;
}

export interface ItemDropControllerUpdateTierRequest {
  id: number;
  updateDropTierDto: UpdateDropTierDto;
}

export interface ItemDropControllerUpdateTradeLinkRequest {
  updateTradeLinkDto: UpdateTradeLinkDto;
}

/**
 * 
 */
export class DropsApi extends runtime.BaseAPI {

    /**
     */
    private async itemDropControllerClaimDropsRaw(): Promise<runtime.ApiResponse<string>> {
        this.itemDropControllerClaimDropsValidation();
        const context = this.itemDropControllerClaimDropsContext();
        const response = await this.request(context);

        return new runtime.TextApiResponse(response) as any;
    }



    /**
     */
    private itemDropControllerClaimDropsValidation() {
    }

    /**
     */
    itemDropControllerClaimDropsContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === "function" ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return {
            path: `/v1/drops/item`,
            method: "POST",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    itemDropControllerClaimDrops = async (): Promise<string> => {
        const response = await this.itemDropControllerClaimDropsRaw();
        return await response.value();
    }


    /**
     */
    private async itemDropControllerCreateDropTierRaw(requestParameters: ItemDropControllerCreateDropTierRequest): Promise<runtime.ApiResponse<void>> {
        this.itemDropControllerCreateDropTierValidation(requestParameters);
        const context = this.itemDropControllerCreateDropTierContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private itemDropControllerCreateDropTierValidation(requestParameters: ItemDropControllerCreateDropTierRequest) {
        if (requestParameters.createDropTierDto === null || requestParameters.createDropTierDto === undefined) {
            throw new runtime.RequiredError("createDropTierDto","Required parameter requestParameters.createDropTierDto was null or undefined when calling itemDropControllerCreateDropTier.");
        }
    }

    /**
     */
    itemDropControllerCreateDropTierContext(requestParameters: ItemDropControllerCreateDropTierRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === "function" ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return {
            path: `/v1/drops/tiers`,
            method: "POST",
            headers: headerParameters,
            query: queryParameters,
            body: CreateDropTierDtoToJSON(requestParameters.createDropTierDto),
        };
    }

    /**
     */
    itemDropControllerCreateDropTier = async (createDropTierDto: CreateDropTierDto): Promise<void> => {
        await this.itemDropControllerCreateDropTierRaw({ createDropTierDto: createDropTierDto });
    }


    /**
     */
    private async itemDropControllerDeleteTierRaw(requestParameters: ItemDropControllerDeleteTierRequest): Promise<runtime.ApiResponse<void>> {
        this.itemDropControllerDeleteTierValidation(requestParameters);
        const context = this.itemDropControllerDeleteTierContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private itemDropControllerDeleteTierValidation(requestParameters: ItemDropControllerDeleteTierRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError("id","Required parameter requestParameters.id was null or undefined when calling itemDropControllerDeleteTier.");
        }
    }

    /**
     */
    itemDropControllerDeleteTierContext(requestParameters: ItemDropControllerDeleteTierRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === "function" ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return {
            path: `/v1/drops/tiers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: "DELETE",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    itemDropControllerDeleteTier = async (id: number): Promise<void> => {
        await this.itemDropControllerDeleteTierRaw({ id: id });
    }

    useItemDropControllerDeleteTier(id: number, config?: SWRConfiguration<void, Error>) {
        let valid = true

        if (id === null || id === undefined || Number.isNaN(id)) {
            valid = false
        }

        const context = this.itemDropControllerDeleteTierContext({ id: id! });
        return useSWR(context, valid ? () => this.itemDropControllerDeleteTier(id!) : null, config)
    }

    /**
     */
    private async itemDropControllerDiscardDropRaw(requestParameters: ItemDropControllerDiscardDropRequest): Promise<runtime.ApiResponse<void>> {
        this.itemDropControllerDiscardDropValidation(requestParameters);
        const context = this.itemDropControllerDiscardDropContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private itemDropControllerDiscardDropValidation(requestParameters: ItemDropControllerDiscardDropRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError("id","Required parameter requestParameters.id was null or undefined when calling itemDropControllerDiscardDrop.");
        }
    }

    /**
     */
    itemDropControllerDiscardDropContext(requestParameters: ItemDropControllerDiscardDropRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === "function" ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return {
            path: `/v1/drops/item/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: "DELETE",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    itemDropControllerDiscardDrop = async (id: string): Promise<void> => {
        await this.itemDropControllerDiscardDropRaw({ id: id });
    }

    useItemDropControllerDiscardDrop(id: string, config?: SWRConfiguration<void, Error>) {
        let valid = true

        if (id === null || id === undefined || Number.isNaN(id)) {
            valid = false
        }

        const context = this.itemDropControllerDiscardDropContext({ id: id! });
        return useSWR(context, valid ? () => this.itemDropControllerDiscardDrop(id!) : null, config)
    }

    /**
     */
    private async itemDropControllerGetDropTiersRaw(): Promise<runtime.ApiResponse<Array<DropTierDto>>> {
        this.itemDropControllerGetDropTiersValidation();
        const context = this.itemDropControllerGetDropTiersContext();
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DropTierDtoFromJSON));
    }



    /**
     */
    private itemDropControllerGetDropTiersValidation() {
    }

    /**
     */
    itemDropControllerGetDropTiersContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === "function" ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return {
            path: `/v1/drops/tiers`,
            method: "GET",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    itemDropControllerGetDropTiers = async (): Promise<Array<DropTierDto>> => {
        const response = await this.itemDropControllerGetDropTiersRaw();
        return await response.value();
    }

    useItemDropControllerGetDropTiers(config?: SWRConfiguration<Array<DropTierDto>, Error>) {
        let valid = true

        const context = this.itemDropControllerGetDropTiersContext();
        return useSWR(context, valid ? () => this.itemDropControllerGetDropTiers() : null, config)
    }

    /**
     */
    private async itemDropControllerGetMyDropsRaw(): Promise<runtime.ApiResponse<Array<DroppedItemDto>>> {
        this.itemDropControllerGetMyDropsValidation();
        const context = this.itemDropControllerGetMyDropsContext();
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DroppedItemDtoFromJSON));
    }



    /**
     */
    private itemDropControllerGetMyDropsValidation() {
    }

    /**
     */
    itemDropControllerGetMyDropsContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === "function" ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return {
            path: `/v1/drops/item`,
            method: "GET",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    itemDropControllerGetMyDrops = async (): Promise<Array<DroppedItemDto>> => {
        const response = await this.itemDropControllerGetMyDropsRaw();
        return await response.value();
    }

    useItemDropControllerGetMyDrops(config?: SWRConfiguration<Array<DroppedItemDto>, Error>) {
        let valid = true

        const context = this.itemDropControllerGetMyDropsContext();
        return useSWR(context, valid ? () => this.itemDropControllerGetMyDrops() : null, config)
    }

    /**
     */
    private async itemDropControllerGetSettingsRaw(): Promise<runtime.ApiResponse<DropSettingsDto>> {
        this.itemDropControllerGetSettingsValidation();
        const context = this.itemDropControllerGetSettingsContext();
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => DropSettingsDtoFromJSON(jsonValue));
    }



    /**
     */
    private itemDropControllerGetSettingsValidation() {
    }

    /**
     */
    itemDropControllerGetSettingsContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === "function" ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return {
            path: `/v1/drops/settings`,
            method: "GET",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    itemDropControllerGetSettings = async (): Promise<DropSettingsDto> => {
        const response = await this.itemDropControllerGetSettingsRaw();
        return await response.value();
    }

    useItemDropControllerGetSettings(config?: SWRConfiguration<DropSettingsDto, Error>) {
        let valid = true

        const context = this.itemDropControllerGetSettingsContext();
        return useSWR(context, valid ? () => this.itemDropControllerGetSettings() : null, config)
    }

    /**
     */
    private async itemDropControllerGetTradesRaw(): Promise<runtime.ApiResponse<Array<TradeOfferDto>>> {
        this.itemDropControllerGetTradesValidation();
        const context = this.itemDropControllerGetTradesContext();
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TradeOfferDtoFromJSON));
    }



    /**
     */
    private itemDropControllerGetTradesValidation() {
    }

    /**
     */
    itemDropControllerGetTradesContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === "function" ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return {
            path: `/v1/drops/user/trades`,
            method: "GET",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    itemDropControllerGetTrades = async (): Promise<Array<TradeOfferDto>> => {
        const response = await this.itemDropControllerGetTradesRaw();
        return await response.value();
    }

    useItemDropControllerGetTrades(config?: SWRConfiguration<Array<TradeOfferDto>, Error>) {
        let valid = true

        const context = this.itemDropControllerGetTradesContext();
        return useSWR(context, valid ? () => this.itemDropControllerGetTrades() : null, config)
    }

    /**
     */
    private async itemDropControllerGetUserRaw(): Promise<runtime.ApiResponse<TradeUserDto>> {
        this.itemDropControllerGetUserValidation();
        const context = this.itemDropControllerGetUserContext();
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TradeUserDtoFromJSON(jsonValue));
    }



    /**
     */
    private itemDropControllerGetUserValidation() {
    }

    /**
     */
    itemDropControllerGetUserContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === "function" ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return {
            path: `/v1/drops/user`,
            method: "GET",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    itemDropControllerGetUser = async (): Promise<TradeUserDto> => {
        const response = await this.itemDropControllerGetUserRaw();
        return await response.value();
    }

    useItemDropControllerGetUser(config?: SWRConfiguration<TradeUserDto, Error>) {
        let valid = true

        const context = this.itemDropControllerGetUserContext();
        return useSWR(context, valid ? () => this.itemDropControllerGetUser() : null, config)
    }

    /**
     */
    private async itemDropControllerPurchaseSubscriptionWithTradeBalanceRaw(requestParameters: ItemDropControllerPurchaseSubscriptionWithTradeBalanceRequest): Promise<runtime.ApiResponse<TradeUserDto>> {
        this.itemDropControllerPurchaseSubscriptionWithTradeBalanceValidation(requestParameters);
        const context = this.itemDropControllerPurchaseSubscriptionWithTradeBalanceContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TradeUserDtoFromJSON(jsonValue));
    }



    /**
     */
    private itemDropControllerPurchaseSubscriptionWithTradeBalanceValidation(requestParameters: ItemDropControllerPurchaseSubscriptionWithTradeBalanceRequest) {
        if (requestParameters.purchaseWithTradeBalanceDto === null || requestParameters.purchaseWithTradeBalanceDto === undefined) {
            throw new runtime.RequiredError("purchaseWithTradeBalanceDto","Required parameter requestParameters.purchaseWithTradeBalanceDto was null or undefined when calling itemDropControllerPurchaseSubscriptionWithTradeBalance.");
        }
    }

    /**
     */
    itemDropControllerPurchaseSubscriptionWithTradeBalanceContext(requestParameters: ItemDropControllerPurchaseSubscriptionWithTradeBalanceRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === "function" ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return {
            path: `/v1/drops/user/subscription`,
            method: "POST",
            headers: headerParameters,
            query: queryParameters,
            body: PurchaseWithTradeBalanceDtoToJSON(requestParameters.purchaseWithTradeBalanceDto),
        };
    }

    /**
     */
    itemDropControllerPurchaseSubscriptionWithTradeBalance = async (purchaseWithTradeBalanceDto: PurchaseWithTradeBalanceDto): Promise<TradeUserDto> => {
        const response = await this.itemDropControllerPurchaseSubscriptionWithTradeBalanceRaw({ purchaseWithTradeBalanceDto: purchaseWithTradeBalanceDto });
        return await response.value();
    }


    /**
     */
    private async itemDropControllerUpdateSettingsRaw(requestParameters: ItemDropControllerUpdateSettingsRequest): Promise<runtime.ApiResponse<void>> {
        this.itemDropControllerUpdateSettingsValidation(requestParameters);
        const context = this.itemDropControllerUpdateSettingsContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private itemDropControllerUpdateSettingsValidation(requestParameters: ItemDropControllerUpdateSettingsRequest) {
        if (requestParameters.updateDropSettingsDto === null || requestParameters.updateDropSettingsDto === undefined) {
            throw new runtime.RequiredError("updateDropSettingsDto","Required parameter requestParameters.updateDropSettingsDto was null or undefined when calling itemDropControllerUpdateSettings.");
        }
    }

    /**
     */
    itemDropControllerUpdateSettingsContext(requestParameters: ItemDropControllerUpdateSettingsRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === "function" ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return {
            path: `/v1/drops/settings`,
            method: "PATCH",
            headers: headerParameters,
            query: queryParameters,
            body: UpdateDropSettingsDtoToJSON(requestParameters.updateDropSettingsDto),
        };
    }

    /**
     */
    itemDropControllerUpdateSettings = async (updateDropSettingsDto: UpdateDropSettingsDto): Promise<void> => {
        await this.itemDropControllerUpdateSettingsRaw({ updateDropSettingsDto: updateDropSettingsDto });
    }


    /**
     */
    private async itemDropControllerUpdateTierRaw(requestParameters: ItemDropControllerUpdateTierRequest): Promise<runtime.ApiResponse<void>> {
        this.itemDropControllerUpdateTierValidation(requestParameters);
        const context = this.itemDropControllerUpdateTierContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private itemDropControllerUpdateTierValidation(requestParameters: ItemDropControllerUpdateTierRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError("id","Required parameter requestParameters.id was null or undefined when calling itemDropControllerUpdateTier.");
        }
        if (requestParameters.updateDropTierDto === null || requestParameters.updateDropTierDto === undefined) {
            throw new runtime.RequiredError("updateDropTierDto","Required parameter requestParameters.updateDropTierDto was null or undefined when calling itemDropControllerUpdateTier.");
        }
    }

    /**
     */
    itemDropControllerUpdateTierContext(requestParameters: ItemDropControllerUpdateTierRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === "function" ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return {
            path: `/v1/drops/tiers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: "PATCH",
            headers: headerParameters,
            query: queryParameters,
            body: UpdateDropTierDtoToJSON(requestParameters.updateDropTierDto),
        };
    }

    /**
     */
    itemDropControllerUpdateTier = async (id: number, updateDropTierDto: UpdateDropTierDto): Promise<void> => {
        await this.itemDropControllerUpdateTierRaw({ id: id, updateDropTierDto: updateDropTierDto });
    }


    /**
     */
    private async itemDropControllerUpdateTradeLinkRaw(requestParameters: ItemDropControllerUpdateTradeLinkRequest): Promise<runtime.ApiResponse<TradeUserDto>> {
        this.itemDropControllerUpdateTradeLinkValidation(requestParameters);
        const context = this.itemDropControllerUpdateTradeLinkContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => TradeUserDtoFromJSON(jsonValue));
    }



    /**
     */
    private itemDropControllerUpdateTradeLinkValidation(requestParameters: ItemDropControllerUpdateTradeLinkRequest) {
        if (requestParameters.updateTradeLinkDto === null || requestParameters.updateTradeLinkDto === undefined) {
            throw new runtime.RequiredError("updateTradeLinkDto","Required parameter requestParameters.updateTradeLinkDto was null or undefined when calling itemDropControllerUpdateTradeLink.");
        }
    }

    /**
     */
    itemDropControllerUpdateTradeLinkContext(requestParameters: ItemDropControllerUpdateTradeLinkRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = typeof token === "function" ? token("bearer", []) : token;

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        return {
            path: `/v1/drops/user`,
            method: "POST",
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTradeLinkDtoToJSON(requestParameters.updateTradeLinkDto),
        };
    }

    /**
     */
    itemDropControllerUpdateTradeLink = async (updateTradeLinkDto: UpdateTradeLinkDto): Promise<TradeUserDto> => {
        const response = await this.itemDropControllerUpdateTradeLinkRaw({ updateTradeLinkDto: updateTradeLinkDto });
        return await response.value();
    }


}
