/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from "../runtime";
import useSWR from "swr";
import { SWRConfiguration } from "swr/_internal";

import {
  CurrentOnlineDto,
  CurrentOnlineDtoFromJSON,
  CurrentOnlineDtoToJSON,
  DemoHighlightsEntity,
  DemoHighlightsEntityFromJSON,
  DemoHighlightsEntityToJSON,
  GameSeasonDto,
  GameSeasonDtoFromJSON,
  GameSeasonDtoToJSON,
  MaintenanceDto,
  MaintenanceDtoFromJSON,
  MaintenanceDtoToJSON,
  MatchmakingInfo,
  MatchmakingInfoFromJSON,
  MatchmakingInfoToJSON,
  TwitchStreamDto,
  TwitchStreamDtoFromJSON,
  TwitchStreamDtoToJSON,
} from "../models";

export interface StatsControllerGetHighlightsRequest {
  id: number;
}

export interface StatsControllerRequestHighlightsRequest {
  id: number;
}

/**
 * 
 */
export class StatsApi extends runtime.BaseAPI {

    /**
     */
    private async statsControllerGetGameSeasonsRaw(): Promise<runtime.ApiResponse<Array<GameSeasonDto>>> {
        this.statsControllerGetGameSeasonsValidation();
        const context = this.statsControllerGetGameSeasonsContext();
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GameSeasonDtoFromJSON));
    }



    /**
     */
    private statsControllerGetGameSeasonsValidation() {
    }

    /**
     */
    statsControllerGetGameSeasonsContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/v1/stats/seasons`,
            method: "GET",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    statsControllerGetGameSeasons = async (): Promise<Array<GameSeasonDto>> => {
        const response = await this.statsControllerGetGameSeasonsRaw();
        return await response.value();
    }

    useStatsControllerGetGameSeasons(config?: SWRConfiguration<Array<GameSeasonDto>, Error>) {
        let valid = true

        const context = this.statsControllerGetGameSeasonsContext();
        return useSWR(context, valid ? () => this.statsControllerGetGameSeasons() : null, config)
    }

    /**
     */
    private async statsControllerGetHighlightsRaw(requestParameters: StatsControllerGetHighlightsRequest): Promise<runtime.ApiResponse<DemoHighlightsEntity>> {
        this.statsControllerGetHighlightsValidation(requestParameters);
        const context = this.statsControllerGetHighlightsContext(requestParameters);
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => DemoHighlightsEntityFromJSON(jsonValue));
    }



    /**
     */
    private statsControllerGetHighlightsValidation(requestParameters: StatsControllerGetHighlightsRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError("id","Required parameter requestParameters.id was null or undefined when calling statsControllerGetHighlights.");
        }
    }

    /**
     */
    statsControllerGetHighlightsContext(requestParameters: StatsControllerGetHighlightsRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/v1/stats/highlights/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: "GET",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    statsControllerGetHighlights = async (id: number): Promise<DemoHighlightsEntity> => {
        const response = await this.statsControllerGetHighlightsRaw({ id: id });
        return await response.value();
    }

    useStatsControllerGetHighlights(id: number, config?: SWRConfiguration<DemoHighlightsEntity, Error>) {
        let valid = true

        if (id === null || id === undefined || Number.isNaN(id)) {
            valid = false
        }

        const context = this.statsControllerGetHighlightsContext({ id: id! });
        return useSWR(context, valid ? () => this.statsControllerGetHighlights(id!) : null, config)
    }

    /**
     */
    private async statsControllerGetMatchmakingInfoRaw(): Promise<runtime.ApiResponse<Array<MatchmakingInfo>>> {
        this.statsControllerGetMatchmakingInfoValidation();
        const context = this.statsControllerGetMatchmakingInfoContext();
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MatchmakingInfoFromJSON));
    }



    /**
     */
    private statsControllerGetMatchmakingInfoValidation() {
    }

    /**
     */
    statsControllerGetMatchmakingInfoContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/v1/stats/matchmaking`,
            method: "GET",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    statsControllerGetMatchmakingInfo = async (): Promise<Array<MatchmakingInfo>> => {
        const response = await this.statsControllerGetMatchmakingInfoRaw();
        return await response.value();
    }

    useStatsControllerGetMatchmakingInfo(config?: SWRConfiguration<Array<MatchmakingInfo>, Error>) {
        let valid = true

        const context = this.statsControllerGetMatchmakingInfoContext();
        return useSWR(context, valid ? () => this.statsControllerGetMatchmakingInfo() : null, config)
    }

    /**
     */
    private async statsControllerGetServersRaw(): Promise<runtime.ApiResponse<Array<string>>> {
        this.statsControllerGetServersValidation();
        const context = this.statsControllerGetServersContext();
        const response = await this.request(context);

        return new runtime.JSONApiResponse<any>(response);
    }



    /**
     */
    private statsControllerGetServersValidation() {
    }

    /**
     */
    statsControllerGetServersContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/v1/stats/servers`,
            method: "GET",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    statsControllerGetServers = async (): Promise<Array<string>> => {
        const response = await this.statsControllerGetServersRaw();
        return await response.value();
    }

    useStatsControllerGetServers(config?: SWRConfiguration<Array<string>, Error>) {
        let valid = true

        const context = this.statsControllerGetServersContext();
        return useSWR(context, valid ? () => this.statsControllerGetServers() : null, config)
    }

    /**
     */
    private async statsControllerGetTwitchStreamsRaw(): Promise<runtime.ApiResponse<Array<TwitchStreamDto>>> {
        this.statsControllerGetTwitchStreamsValidation();
        const context = this.statsControllerGetTwitchStreamsContext();
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TwitchStreamDtoFromJSON));
    }



    /**
     */
    private statsControllerGetTwitchStreamsValidation() {
    }

    /**
     */
    statsControllerGetTwitchStreamsContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/v1/stats/twitch`,
            method: "GET",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    statsControllerGetTwitchStreams = async (): Promise<Array<TwitchStreamDto>> => {
        const response = await this.statsControllerGetTwitchStreamsRaw();
        return await response.value();
    }

    useStatsControllerGetTwitchStreams(config?: SWRConfiguration<Array<TwitchStreamDto>, Error>) {
        let valid = true

        const context = this.statsControllerGetTwitchStreamsContext();
        return useSWR(context, valid ? () => this.statsControllerGetTwitchStreams() : null, config)
    }

    /**
     */
    private async statsControllerMaintenanceRaw(): Promise<runtime.ApiResponse<MaintenanceDto>> {
        this.statsControllerMaintenanceValidation();
        const context = this.statsControllerMaintenanceContext();
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => MaintenanceDtoFromJSON(jsonValue));
    }



    /**
     */
    private statsControllerMaintenanceValidation() {
    }

    /**
     */
    statsControllerMaintenanceContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/v1/stats/maintenance`,
            method: "GET",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    statsControllerMaintenance = async (): Promise<MaintenanceDto> => {
        const response = await this.statsControllerMaintenanceRaw();
        return await response.value();
    }

    useStatsControllerMaintenance(config?: SWRConfiguration<MaintenanceDto, Error>) {
        let valid = true

        const context = this.statsControllerMaintenanceContext();
        return useSWR(context, valid ? () => this.statsControllerMaintenance() : null, config)
    }

    /**
     */
    private async statsControllerOnlineRaw(): Promise<runtime.ApiResponse<CurrentOnlineDto>> {
        this.statsControllerOnlineValidation();
        const context = this.statsControllerOnlineContext();
        const response = await this.request(context);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurrentOnlineDtoFromJSON(jsonValue));
    }



    /**
     */
    private statsControllerOnlineValidation() {
    }

    /**
     */
    statsControllerOnlineContext(): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/v1/stats/online`,
            method: "GET",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    statsControllerOnline = async (): Promise<CurrentOnlineDto> => {
        const response = await this.statsControllerOnlineRaw();
        return await response.value();
    }

    useStatsControllerOnline(config?: SWRConfiguration<CurrentOnlineDto, Error>) {
        let valid = true

        const context = this.statsControllerOnlineContext();
        return useSWR(context, valid ? () => this.statsControllerOnline() : null, config)
    }

    /**
     */
    private async statsControllerRequestHighlightsRaw(requestParameters: StatsControllerRequestHighlightsRequest): Promise<runtime.ApiResponse<void>> {
        this.statsControllerRequestHighlightsValidation(requestParameters);
        const context = this.statsControllerRequestHighlightsContext(requestParameters);
        const response = await this.request(context);

        return new runtime.VoidApiResponse(response);
    }



    /**
     */
    private statsControllerRequestHighlightsValidation(requestParameters: StatsControllerRequestHighlightsRequest) {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError("id","Required parameter requestParameters.id was null or undefined when calling statsControllerRequestHighlights.");
        }
    }

    /**
     */
    statsControllerRequestHighlightsContext(requestParameters: StatsControllerRequestHighlightsRequest): runtime.RequestOpts {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        return {
            path: `/v1/stats/highlights/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: "POST",
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    statsControllerRequestHighlights = async (id: number): Promise<void> => {
        await this.statsControllerRequestHighlightsRaw({ id: id });
    }


}
