export type HeroName = { hero: string; localizedName: string };

export const HeroNames: HeroName[] = [
  { hero: "npc_dota_hero_antimage", localizedName: "Anti-Mage" },
  { hero: "npc_dota_hero_axe", localizedName: "Axe" },
  { hero: "npc_dota_hero_bane", localizedName: "Bane" },
  { hero: "npc_dota_hero_bloodseeker", localizedName: "Bloodseeker" },
  { hero: "npc_dota_hero_crystal_maiden", localizedName: "Crystal Maiden" },
  { hero: "npc_dota_hero_drow_ranger", localizedName: "Drow Ranger" },
  { hero: "npc_dota_hero_earthshaker", localizedName: "Earthshaker" },
  { hero: "npc_dota_hero_juggernaut", localizedName: "Juggernaut" },
  { hero: "npc_dota_hero_mirana", localizedName: "Mirana" },
  { hero: "npc_dota_hero_morphling", localizedName: "Morphling" },
  { hero: "npc_dota_hero_nevermore", localizedName: "Shadow Fiend" },
  { hero: "npc_dota_hero_phantom_lancer", localizedName: "Phantom Lancer" },
  { hero: "npc_dota_hero_puck", localizedName: "Puck" },
  { hero: "npc_dota_hero_pudge", localizedName: "Pudge" },
  { hero: "npc_dota_hero_razor", localizedName: "Razor" },
  { hero: "npc_dota_hero_sand_king", localizedName: "Sand King" },
  { hero: "npc_dota_hero_storm_spirit", localizedName: "Storm Spirit" },
  { hero: "npc_dota_hero_sven", localizedName: "Sven" },
  { hero: "npc_dota_hero_tiny", localizedName: "Tiny" },
  { hero: "npc_dota_hero_vengefulspirit", localizedName: "Vengeful Spirit" },
  { hero: "npc_dota_hero_windrunner", localizedName: "Windranger" },
  { hero: "npc_dota_hero_zuus", localizedName: "Zeus" },
  { hero: "npc_dota_hero_kunkka", localizedName: "Kunkka" },
  { hero: "npc_dota_hero_lina", localizedName: "Lina" },
  { hero: "npc_dota_hero_lion", localizedName: "Lion" },
  { hero: "npc_dota_hero_shadow_shaman", localizedName: "Shadow Shaman" },
  { hero: "npc_dota_hero_slardar", localizedName: "Slardar" },
  { hero: "npc_dota_hero_tidehunter", localizedName: "Tidehunter" },
  { hero: "npc_dota_hero_witch_doctor", localizedName: "Witch Doctor" },
  { hero: "npc_dota_hero_lich", localizedName: "Lich" },
  { hero: "npc_dota_hero_riki", localizedName: "Riki" },
  { hero: "npc_dota_hero_enigma", localizedName: "Enigma" },
  { hero: "npc_dota_hero_tinker", localizedName: "Tinker" },
  { hero: "npc_dota_hero_sniper", localizedName: "Sniper" },
  { hero: "npc_dota_hero_necrolyte", localizedName: "Necrophos" },
  { hero: "npc_dota_hero_warlock", localizedName: "Warlock" },
  { hero: "npc_dota_hero_beastmaster", localizedName: "Beastmaster" },
  { hero: "npc_dota_hero_queenofpain", localizedName: "Queen of Pain" },
  { hero: "npc_dota_hero_venomancer", localizedName: "Venomancer" },
  { hero: "npc_dota_hero_faceless_void", localizedName: "Faceless Void" },
  { hero: "npc_dota_hero_skeleton_king", localizedName: "Wraith King" },
  { hero: "npc_dota_hero_death_prophet", localizedName: "Death Prophet" },
  { hero: "npc_dota_hero_phantom_assassin", localizedName: "Phantom Assassin" },
  { hero: "npc_dota_hero_pugna", localizedName: "Pugna" },
  { hero: "npc_dota_hero_templar_assassin", localizedName: "Templar Assassin" },
  { hero: "npc_dota_hero_viper", localizedName: "Viper" },
  { hero: "npc_dota_hero_luna", localizedName: "Luna" },
  { hero: "npc_dota_hero_dragon_knight", localizedName: "Dragon Knight" },
  { hero: "npc_dota_hero_dazzle", localizedName: "Dazzle" },
  { hero: "npc_dota_hero_rattletrap", localizedName: "Clockwerk" },
  { hero: "npc_dota_hero_leshrac", localizedName: "Leshrac" },
  { hero: "npc_dota_hero_furion", localizedName: "Nature's Prophet" },
  { hero: "npc_dota_hero_life_stealer", localizedName: "Lifestealer" },
  { hero: "npc_dota_hero_dark_seer", localizedName: "Dark Seer" },
  { hero: "npc_dota_hero_clinkz", localizedName: "Clinkz" },
  { hero: "npc_dota_hero_omniknight", localizedName: "Omniknight" },
  { hero: "npc_dota_hero_enchantress", localizedName: "Enchantress" },
  { hero: "npc_dota_hero_huskar", localizedName: "Huskar" },
  { hero: "npc_dota_hero_night_stalker", localizedName: "Night Stalker" },
  { hero: "npc_dota_hero_broodmother", localizedName: "Broodmother" },
  { hero: "npc_dota_hero_bounty_hunter", localizedName: "Bounty Hunter" },
  { hero: "npc_dota_hero_weaver", localizedName: "Weaver" },
  { hero: "npc_dota_hero_jakiro", localizedName: "Jakiro" },
  { hero: "npc_dota_hero_batrider", localizedName: "Batrider" },
  { hero: "npc_dota_hero_chen", localizedName: "Chen" },
  { hero: "npc_dota_hero_spectre", localizedName: "Spectre" },
  {
    hero: "npc_dota_hero_ancient_apparition",
    localizedName: "Ancient Apparition",
  },
  { hero: "npc_dota_hero_doom_bringer", localizedName: "Doom" },
  { hero: "npc_dota_hero_ursa", localizedName: "Ursa" },
  { hero: "npc_dota_hero_spirit_breaker", localizedName: "Spirit Breaker" },
  { hero: "npc_dota_hero_gyrocopter", localizedName: "Gyrocopter" },
  { hero: "npc_dota_hero_alchemist", localizedName: "Alchemist" },
  { hero: "npc_dota_hero_invoker", localizedName: "Invoker" },
  { hero: "npc_dota_hero_silencer", localizedName: "Silencer" },
  {
    hero: "npc_dota_hero_obsidian_destroyer",
    localizedName: "Outworld Devourer",
  },
  { hero: "npc_dota_hero_lycan", localizedName: "Lycan" },
  { hero: "npc_dota_hero_brewmaster", localizedName: "Brewmaster" },
  { hero: "npc_dota_hero_shadow_demon", localizedName: "Shadow Demon" },
  { hero: "npc_dota_hero_lone_druid", localizedName: "Lone Druid" },
  { hero: "npc_dota_hero_chaos_knight", localizedName: "Chaos Knight" },
  { hero: "npc_dota_hero_meepo", localizedName: "Meepo" },
  { hero: "npc_dota_hero_treant", localizedName: "Treant Protector" },
  { hero: "npc_dota_hero_ogre_magi", localizedName: "Ogre Magi" },
  { hero: "npc_dota_hero_undying", localizedName: "Undying" },
  { hero: "npc_dota_hero_rubick", localizedName: "Rubick" },
  { hero: "npc_dota_hero_disruptor", localizedName: "Disruptor" },
  { hero: "npc_dota_hero_nyx_assassin", localizedName: "Nyx Assassin" },
  { hero: "npc_dota_hero_naga_siren", localizedName: "Naga Siren" },
  {
    hero: "npc_dota_hero_keeper_of_the_light",
    localizedName: "Keeper of the Light",
  },
  { hero: "npc_dota_hero_wisp", localizedName: "Io" },
  { hero: "npc_dota_hero_visage", localizedName: "Visage" },
  { hero: "npc_dota_hero_slark", localizedName: "Slark" },
  { hero: "npc_dota_hero_medusa", localizedName: "Medusa" },
  { hero: "npc_dota_hero_troll_warlord", localizedName: "Troll Warlord" },
  { hero: "npc_dota_hero_centaur", localizedName: "Centaur Warrunner" },
  { hero: "npc_dota_hero_magnataur", localizedName: "Magnus" },
  { hero: "npc_dota_hero_shredder", localizedName: "Timbersaw" },
  { hero: "npc_dota_hero_bristleback", localizedName: "Bristleback" },
  { hero: "npc_dota_hero_tusk", localizedName: "Tusk" },
  { hero: "npc_dota_hero_skywrath_mage", localizedName: "Skywrath Mage" },
  { hero: "npc_dota_hero_abaddon", localizedName: "Abaddon" },
  { hero: "npc_dota_hero_elder_titan", localizedName: "Elder Titan" },
  { hero: "npc_dota_hero_legion_commander", localizedName: "Legion Commander" },
  { hero: "npc_dota_hero_techies", localizedName: "Techies" },
  { hero: "npc_dota_hero_ember_spirit", localizedName: "Ember Spirit" },
  { hero: "npc_dota_hero_earth_spirit", localizedName: "Earth Spirit" },
  { hero: "npc_dota_hero_abyssal_underlord", localizedName: "Underlord" },
  { hero: "npc_dota_hero_terrorblade", localizedName: "Terrorblade" },
  { hero: "npc_dota_hero_phoenix", localizedName: "Phoenix" },
  { hero: "npc_dota_hero_oracle", localizedName: "Oracle" },
  { hero: "npc_dota_hero_winter_wyvern", localizedName: "Winter Wyvern" },
];
