/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplyPunishmentDto
 */
export interface ApplyPunishmentDto {
    /**
     * 
     * @type {string}
     * @memberof ApplyPunishmentDto
     */
    steamId: string;
    /**
     * 
     * @type {number}
     * @memberof ApplyPunishmentDto
     */
    ruleId: number;
    /**
     * 
     * @type {number}
     * @memberof ApplyPunishmentDto
     */
    overridePunishmentId?: number;
}

export function ApplyPunishmentDtoFromJSON(json: any): ApplyPunishmentDto {
    return ApplyPunishmentDtoFromJSONTyped(json, false);
}

export function ApplyPunishmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplyPunishmentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'steamId': json['steamId'],
        'ruleId': json['ruleId'],
        'overridePunishmentId': !exists(json, 'overridePunishmentId') ? undefined : json['overridePunishmentId'],
    };
}

export function ApplyPunishmentDtoToJSON(value?: ApplyPunishmentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'steamId': value.steamId,
        'ruleId': value.ruleId,
        'overridePunishmentId': value.overridePunishmentId,
    };
}


