/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMessageDTO
 */
export interface CreateMessageDTO {
    /**
     * 
     * @type {string}
     * @memberof CreateMessageDTO
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMessageDTO
     */
    threadId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMessageDTO
     */
    replyMessageId?: string;
}

export function CreateMessageDTOFromJSON(json: any): CreateMessageDTO {
    return CreateMessageDTOFromJSONTyped(json, false);
}

export function CreateMessageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMessageDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': json['content'],
        'threadId': json['threadId'],
        'replyMessageId': !exists(json, 'replyMessageId') ? undefined : json['replyMessageId'],
    };
}

export function CreateMessageDTOToJSON(value?: CreateMessageDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
        'threadId': value.threadId,
        'replyMessageId': value.replyMessageId,
    };
}


