/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFeedbackOptionDto
 */
export interface CreateFeedbackOptionDto {
    /**
     * 
     * @type {string}
     * @memberof CreateFeedbackOptionDto
     */
    option: string;
}

export function CreateFeedbackOptionDtoFromJSON(json: any): CreateFeedbackOptionDto {
    return CreateFeedbackOptionDtoFromJSONTyped(json, false);
}

export function CreateFeedbackOptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFeedbackOptionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'option': json['option'],
    };
}

export function CreateFeedbackOptionDtoToJSON(value?: CreateFeedbackOptionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'option': value.option,
    };
}


