/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRuleDto
 */
export interface CreateRuleDto {
    /**
     * 
     * @type {number}
     * @memberof CreateRuleDto
     */
    parent?: number;
}

export function CreateRuleDtoFromJSON(json: any): CreateRuleDto {
    return CreateRuleDtoFromJSONTyped(json, false);
}

export function CreateRuleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRuleDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parent': !exists(json, 'parent') ? undefined : json['parent'],
    };
}

export function CreateRuleDtoToJSON(value?: CreateRuleDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent': value.parent,
    };
}


