/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFeedbackDto
 */
export interface CreateFeedbackDto {
    /**
     * 
     * @type {string}
     * @memberof CreateFeedbackDto
     */
    tag: string;
    /**
     * 
     * @type {string}
     * @memberof CreateFeedbackDto
     */
    title: string;
}

export function CreateFeedbackDtoFromJSON(json: any): CreateFeedbackDto {
    return CreateFeedbackDtoFromJSONTyped(json, false);
}

export function CreateFeedbackDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFeedbackDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tag': json['tag'],
        'title': json['title'],
    };
}

export function CreateFeedbackDtoToJSON(value?: CreateFeedbackDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tag': value.tag,
        'title': value.title,
    };
}


