/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePaymentItemDto
 */
export interface CreatePaymentItemDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentItemDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentItemDto
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePaymentItemDto
     */
    amount: number;
}

export function CreatePaymentItemDtoFromJSON(json: any): CreatePaymentItemDto {
    return CreatePaymentItemDtoFromJSONTyped(json, false);
}

export function CreatePaymentItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentItemDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'quantity': json['quantity'],
        'amount': json['amount'],
    };
}

export function CreatePaymentItemDtoToJSON(value?: CreatePaymentItemDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'quantity': value.quantity,
        'amount': value.amount,
    };
}


