/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserProfileDecorationType,
    UserProfileDecorationTypeFromJSON,
    UserProfileDecorationTypeFromJSONTyped,
    UserProfileDecorationTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateDecorationDto
 */
export interface CreateDecorationDto {
    /**
     * 
     * @type {UserProfileDecorationType}
     * @memberof CreateDecorationDto
     */
    type: UserProfileDecorationType;
    /**
     * 
     * @type {string}
     * @memberof CreateDecorationDto
     */
    imageKey: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDecorationDto
     */
    title: string;
}

export function CreateDecorationDtoFromJSON(json: any): CreateDecorationDto {
    return CreateDecorationDtoFromJSONTyped(json, false);
}

export function CreateDecorationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDecorationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': UserProfileDecorationTypeFromJSON(json['type']),
        'imageKey': json['imageKey'],
        'title': json['title'],
    };
}

export function CreateDecorationDtoToJSON(value?: CreateDecorationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': UserProfileDecorationTypeToJSON(value.type),
        'imageKey': value.imageKey,
        'title': value.title,
    };
}


