/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CrimeLogDto,
    CrimeLogDtoFromJSON,
    CrimeLogDtoFromJSONTyped,
    CrimeLogDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CrimeLogPageDto
 */
export interface CrimeLogPageDto {
    /**
     * 
     * @type {Array<CrimeLogDto>}
     * @memberof CrimeLogPageDto
     */
    data: Array<CrimeLogDto>;
    /**
     * 
     * @type {number}
     * @memberof CrimeLogPageDto
     */
    pages: number;
    /**
     * 
     * @type {number}
     * @memberof CrimeLogPageDto
     */
    perPage: number;
    /**
     * 
     * @type {number}
     * @memberof CrimeLogPageDto
     */
    page: number;
}

export function CrimeLogPageDtoFromJSON(json: any): CrimeLogPageDto {
    return CrimeLogPageDtoFromJSONTyped(json, false);
}

export function CrimeLogPageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrimeLogPageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CrimeLogDtoFromJSON)),
        'pages': json['pages'],
        'perPage': json['perPage'],
        'page': json['page'],
    };
}

export function CrimeLogPageDtoToJSON(value?: CrimeLogPageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(CrimeLogDtoToJSON)),
        'pages': value.pages,
        'perPage': value.perPage,
        'page': value.page,
    };
}


