/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PerModePlayersDto,
    PerModePlayersDtoFromJSON,
    PerModePlayersDtoFromJSONTyped,
    PerModePlayersDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CurrentOnlineDto
 */
export interface CurrentOnlineDto {
    /**
     * 
     * @type {number}
     * @memberof CurrentOnlineDto
     */
    inGame: number;
    /**
     * 
     * @type {number}
     * @memberof CurrentOnlineDto
     */
    sessions: number;
    /**
     * 
     * @type {number}
     * @memberof CurrentOnlineDto
     */
    servers: number;
    /**
     * 
     * @type {Array<PerModePlayersDto>}
     * @memberof CurrentOnlineDto
     */
    perMode: Array<PerModePlayersDto>;
}

export function CurrentOnlineDtoFromJSON(json: any): CurrentOnlineDto {
    return CurrentOnlineDtoFromJSONTyped(json, false);
}

export function CurrentOnlineDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentOnlineDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inGame': json['inGame'],
        'sessions': json['sessions'],
        'servers': json['servers'],
        'perMode': ((json['perMode'] as Array<any>).map(PerModePlayersDtoFromJSON)),
    };
}

export function CurrentOnlineDtoToJSON(value?: CurrentOnlineDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'inGame': value.inGame,
        'sessions': value.sessions,
        'servers': value.servers,
        'perMode': ((value.perMode as Array<any>).map(PerModePlayersDtoToJSON)),
    };
}


