/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackTemplateOptionDto
 */
export interface FeedbackTemplateOptionDto {
    /**
     * 
     * @type {number}
     * @memberof FeedbackTemplateOptionDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackTemplateOptionDto
     */
    option: string;
}

export function FeedbackTemplateOptionDtoFromJSON(json: any): FeedbackTemplateOptionDto {
    return FeedbackTemplateOptionDtoFromJSONTyped(json, false);
}

export function FeedbackTemplateOptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackTemplateOptionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'option': json['option'],
    };
}

export function FeedbackTemplateOptionDtoToJSON(value?: FeedbackTemplateOptionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'option': value.option,
    };
}


