/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FeedbackTemplateOptionDto,
    FeedbackTemplateOptionDtoFromJSON,
    FeedbackTemplateOptionDtoFromJSONTyped,
    FeedbackTemplateOptionDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface FeedbackTemplateDto
 */
export interface FeedbackTemplateDto {
    /**
     * 
     * @type {number}
     * @memberof FeedbackTemplateDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackTemplateDto
     */
    tag: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackTemplateDto
     */
    title: string;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackTemplateDto
     */
    needsTicket: boolean;
    /**
     * 
     * @type {Array<FeedbackTemplateOptionDto>}
     * @memberof FeedbackTemplateDto
     */
    options: Array<FeedbackTemplateOptionDto>;
}

export function FeedbackTemplateDtoFromJSON(json: any): FeedbackTemplateDto {
    return FeedbackTemplateDtoFromJSONTyped(json, false);
}

export function FeedbackTemplateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackTemplateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tag': json['tag'],
        'title': json['title'],
        'needsTicket': json['needsTicket'],
        'options': ((json['options'] as Array<any>).map(FeedbackTemplateOptionDtoFromJSON)),
    };
}

export function FeedbackTemplateDtoToJSON(value?: FeedbackTemplateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'tag': value.tag,
        'title': value.title,
        'needsTicket': value.needsTicket,
        'options': ((value.options as Array<any>).map(FeedbackTemplateOptionDtoToJSON)),
    };
}


