/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GamemodeAccessMap
 */
export interface GamemodeAccessMap {
    /**
     * 
     * @type {boolean}
     * @memberof GamemodeAccessMap
     */
    education: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GamemodeAccessMap
     */
    simpleModes: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GamemodeAccessMap
     */
    humanGames: boolean;
}

export function GamemodeAccessMapFromJSON(json: any): GamemodeAccessMap {
    return GamemodeAccessMapFromJSONTyped(json, false);
}

export function GamemodeAccessMapFromJSONTyped(json: any, ignoreDiscriminator: boolean): GamemodeAccessMap {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'education': json['education'],
        'simpleModes': json['simpleModes'],
        'humanGames': json['humanGames'],
    };
}

export function GamemodeAccessMapToJSON(value?: GamemodeAccessMap | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'education': value.education,
        'simpleModes': value.simpleModes,
        'humanGames': value.humanGames,
    };
}


