/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameSeasonDto
 */
export interface GameSeasonDto {
    /**
     * 
     * @type {number}
     * @memberof GameSeasonDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GameSeasonDto
     */
    startTimestamp: string;
    /**
     * 
     * @type {boolean}
     * @memberof GameSeasonDto
     */
    isActive: boolean;
}

export function GameSeasonDtoFromJSON(json: any): GameSeasonDto {
    return GameSeasonDtoFromJSONTyped(json, false);
}

export function GameSeasonDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameSeasonDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startTimestamp': json['startTimestamp'],
        'isActive': json['isActive'],
    };
}

export function GameSeasonDtoToJSON(value?: GameSeasonDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'startTimestamp': value.startTimestamp,
        'isActive': value.isActive,
    };
}


