/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface HeroStatsDto
 */
export interface HeroStatsDto {
  /**
   *
   * @type {string}
   * @memberof HeroStatsDto
   */
  playerId: string;
  /**
   *
   * @type {number}
   * @memberof HeroStatsDto
   */
  gpm: number;
  /**
   *
   * @type {number}
   * @memberof HeroStatsDto
   */
  xpm: number;
  /**
   *
   * @type {number}
   * @memberof HeroStatsDto
   */
  kda: number;
  /**
   *
   * @type {number}
   * @memberof HeroStatsDto
   */
  games: number;
  /**
   *
   * @type {number}
   * @memberof HeroStatsDto
   */
  wins: number;
  /**
   *
   * @type {number}
   * @memberof HeroStatsDto
   */
  loss: number;
  /**
   *
   * @type {string}
   * @memberof HeroStatsDto
   */
  hero: string;
  /**
   *
   * @type {number}
   * @memberof HeroStatsDto
   */
  lastHits: number;
  /**
   *
   * @type {number}
   * @memberof HeroStatsDto
   */
  denies: number;
}

export function HeroStatsDtoFromJSON(json: any): HeroStatsDto {
  return HeroStatsDtoFromJSONTyped(json, false);
}

export function HeroStatsDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): HeroStatsDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    playerId: json["playerId"],
    gpm: json["gpm"],
    xpm: json["xpm"],
    kda: json["kda"],
    games: json["games"],
    wins: json["wins"],
    loss: json["loss"],
    hero: json["hero"],
    lastHits: json["last_hits"],
    denies: json["denies"],
  };
}

export function HeroStatsDtoToJSON(value?: HeroStatsDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    playerId: value.playerId,
    gpm: value.gpm,
    xpm: value.xpm,
    kda: value.kda,
    games: value.games,
    wins: value.wins,
    loss: value.loss,
    hero: value.hero,
    last_hits: value.lastHits,
    denies: value.denies,
  };
}
