/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  UserDTO,
  UserDTOFromJSON,
  UserDTOFromJSONTyped,
  UserDTOToJSON,
} from "./";

/**
 *
 * @export
 * @interface HeroPlayerDto
 */
export interface HeroPlayerDto {
  /**
   *
   * @type {UserDTO}
   * @memberof HeroPlayerDto
   */
  user: UserDTO;
  /**
   *
   * @type {number}
   * @memberof HeroPlayerDto
   */
  games: number;
  /**
   *
   * @type {number}
   * @memberof HeroPlayerDto
   */
  wins: number;
  /**
   *
   * @type {number}
   * @memberof HeroPlayerDto
   */
  score: number;
  /**
   *
   * @type {number}
   * @memberof HeroPlayerDto
   */
  kills: number;
  /**
   *
   * @type {number}
   * @memberof HeroPlayerDto
   */
  deaths: number;
  /**
   *
   * @type {number}
   * @memberof HeroPlayerDto
   */
  assists: number;
}

export function HeroPlayerDtoFromJSON(json: any): HeroPlayerDto {
  return HeroPlayerDtoFromJSONTyped(json, false);
}

export function HeroPlayerDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): HeroPlayerDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: UserDTOFromJSON(json["user"]),
    games: json["games"],
    wins: json["wins"],
    score: json["score"],
    kills: json["kills"],
    deaths: json["deaths"],
    assists: json["assists"],
  };
}

export function HeroPlayerDtoToJSON(value?: HeroPlayerDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user: UserDTOToJSON(value.user),
    games: value.games,
    wins: value.wins,
    score: value.score,
    kills: value.kills,
    deaths: value.deaths,
    assists: value.assists,
  };
}
