/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteToRegistrationDto
 */
export interface InviteToRegistrationDto {
    /**
     * 
     * @type {string}
     * @memberof InviteToRegistrationDto
     */
    steamId: string;
}

export function InviteToRegistrationDtoFromJSON(json: any): InviteToRegistrationDto {
    return InviteToRegistrationDtoFromJSONTyped(json, false);
}

export function InviteToRegistrationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteToRegistrationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'steamId': json['steamId'],
    };
}

export function InviteToRegistrationDtoToJSON(value?: InviteToRegistrationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'steamId': value.steamId,
    };
}


