/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ItemDto
 */
export interface ItemDto {
  /**
   *
   * @type {number}
   * @memberof ItemDto
   */
  item: number;
  /**
   *
   * @type {number}
   * @memberof ItemDto
   */
  popularity: number;
  /**
   *
   * @type {number}
   * @memberof ItemDto
   */
  games: number;
  /**
   *
   * @type {number}
   * @memberof ItemDto
   */
  wins: number;
}

export function ItemDtoFromJSON(json: any): ItemDto {
  return ItemDtoFromJSONTyped(json, false);
}

export function ItemDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ItemDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    item: json["item"],
    popularity: json["popularity"],
    games: json["games"],
    wins: json["wins"],
  };
}

export function ItemDtoToJSON(value?: ItemDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    item: value.item,
    popularity: value.popularity,
    games: value.games,
    wins: value.wins,
  };
}
