/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LeaderboardEntryDto,
    LeaderboardEntryDtoFromJSON,
    LeaderboardEntryDtoFromJSONTyped,
    LeaderboardEntryDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface LeaderboardEntryPageDto
 */
export interface LeaderboardEntryPageDto {
    /**
     * 
     * @type {Array<LeaderboardEntryDto>}
     * @memberof LeaderboardEntryPageDto
     */
    data: Array<LeaderboardEntryDto>;
    /**
     * 
     * @type {number}
     * @memberof LeaderboardEntryPageDto
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof LeaderboardEntryPageDto
     */
    perPage: number;
    /**
     * 
     * @type {number}
     * @memberof LeaderboardEntryPageDto
     */
    pages: number;
}

export function LeaderboardEntryPageDtoFromJSON(json: any): LeaderboardEntryPageDto {
    return LeaderboardEntryPageDtoFromJSONTyped(json, false);
}

export function LeaderboardEntryPageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardEntryPageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(LeaderboardEntryDtoFromJSON)),
        'page': json['page'],
        'perPage': json['perPage'],
        'pages': json['pages'],
    };
}

export function LeaderboardEntryPageDtoToJSON(value?: LeaderboardEntryPageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(LeaderboardEntryDtoToJSON)),
        'page': value.page,
        'perPage': value.perPage,
        'pages': value.pages,
    };
}


