/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  LiveMatchDto,
  LiveMatchDtoFromJSON,
  LiveMatchDtoFromJSONTyped,
  LiveMatchDtoToJSON,
} from "./";

/**
 *
 * @export
 * @interface LiveMatchSseDto
 */
export interface LiveMatchSseDto {
  /**
   *
   * @type {LiveMatchDto}
   * @memberof LiveMatchSseDto
   */
  data: LiveMatchDto;
  /**
   *
   * @type {string}
   * @memberof LiveMatchSseDto
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof LiveMatchSseDto
   */
  type?: string;
  /**
   *
   * @type {number}
   * @memberof LiveMatchSseDto
   */
  retry?: number;
}

export function LiveMatchSseDtoFromJSON(json: any): LiveMatchSseDto {
  return LiveMatchSseDtoFromJSONTyped(json, false);
}

export function LiveMatchSseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LiveMatchSseDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: LiveMatchDtoFromJSON(json["data"]),
    id: !exists(json, "id") ? undefined : json["id"],
    type: !exists(json, "type") ? undefined : json["type"],
    retry: !exists(json, "retry") ? undefined : json["retry"],
  };
}

export function LiveMatchSseDtoToJSON(value?: LiveMatchSseDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: LiveMatchDtoToJSON(value.data),
    id: value.id,
    type: value.type,
    retry: value.retry,
  };
}
