/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PlayerInfo,
    PlayerInfoFromJSON,
    PlayerInfoFromJSONTyped,
    PlayerInfoToJSON,
} from './';

/**
 * 
 * @export
 * @interface LiveMatchDto
 */
export interface LiveMatchDto {
    /**
     * 
     * @type {number}
     * @memberof LiveMatchDto
     */
    matchId: number;
    /**
     * 
     * @type {number}
     * @memberof LiveMatchDto
     */
    type: LiveMatchDtoTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof LiveMatchDto
     */
    duration: number;
    /**
     * 
     * @type {string}
     * @memberof LiveMatchDto
     */
    server: string;
    /**
     * 
     * @type {number}
     * @memberof LiveMatchDto
     */
    timestamp: number;
    /**
     * 
     * @type {Array<PlayerInfo>}
     * @memberof LiveMatchDto
     */
    heroes: Array<PlayerInfo>;
}

export function LiveMatchDtoFromJSON(json: any): LiveMatchDto {
    return LiveMatchDtoFromJSONTyped(json, false);
}

export function LiveMatchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LiveMatchDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'matchId': json['matchId'],
        'type': json['type'],
        'duration': json['duration'],
        'server': json['server'],
        'timestamp': json['timestamp'],
        'heroes': ((json['heroes'] as Array<any>).map(PlayerInfoFromJSON)),
    };
}

export function LiveMatchDtoToJSON(value?: LiveMatchDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'matchId': value.matchId,
        'type': value.type,
        'duration': value.duration,
        'server': value.server,
        'timestamp': value.timestamp,
        'heroes': ((value.heroes as Array<any>).map(PlayerInfoToJSON)),
    };
}

/**
* @export
* @enum {string}
*/
export enum LiveMatchDtoTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10
}


