/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DotaGameMode,
    DotaGameModeFromJSON,
    DotaGameModeFromJSONTyped,
    DotaGameModeToJSON,
    DotaMap,
    DotaMapFromJSON,
    DotaMapFromJSONTyped,
    DotaMapToJSON,
    DotaPatch,
    DotaPatchFromJSON,
    DotaPatchFromJSONTyped,
    DotaPatchToJSON,
    LobbySlotDto,
    LobbySlotDtoFromJSON,
    LobbySlotDtoFromJSONTyped,
    LobbySlotDtoToJSON,
    Region,
    RegionFromJSON,
    RegionFromJSONTyped,
    RegionToJSON,
    UserDTO,
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface LobbyDto
 */
export interface LobbyDto {
    /**
     * 
     * @type {DotaGameMode}
     * @memberof LobbyDto
     */
    gameMode: DotaGameMode;
    /**
     * 
     * @type {DotaMap}
     * @memberof LobbyDto
     */
    map: DotaMap;
    /**
     * 
     * @type {DotaPatch}
     * @memberof LobbyDto
     */
    patch: DotaPatch;
    /**
     * 
     * @type {Region}
     * @memberof LobbyDto
     */
    region: Region;
    /**
     * 
     * @type {string}
     * @memberof LobbyDto
     */
    id: string;
    /**
     * 
     * @type {UserDTO}
     * @memberof LobbyDto
     */
    owner: UserDTO;
    /**
     * 
     * @type {Array<LobbySlotDto>}
     * @memberof LobbyDto
     */
    slots: Array<LobbySlotDto>;
    /**
     * 
     * @type {string}
     * @memberof LobbyDto
     */
    password?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LobbyDto
     */
    requiresPassword: boolean;
    /**
     * 
     * @type {string}
     * @memberof LobbyDto
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof LobbyDto
     */
    fillBots: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LobbyDto
     */
    enableCheats: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LobbyDto
     */
    noRunes: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof LobbyDto
     */
    midTowerToWin: boolean;
    /**
     * 
     * @type {number}
     * @memberof LobbyDto
     */
    midTowerKillsToWin: number;
}

export function LobbyDtoFromJSON(json: any): LobbyDto {
    return LobbyDtoFromJSONTyped(json, false);
}

export function LobbyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LobbyDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gameMode': DotaGameModeFromJSON(json['gameMode']),
        'map': DotaMapFromJSON(json['map']),
        'patch': DotaPatchFromJSON(json['patch']),
        'region': RegionFromJSON(json['region']),
        'id': json['id'],
        'owner': UserDTOFromJSON(json['owner']),
        'slots': ((json['slots'] as Array<any>).map(LobbySlotDtoFromJSON)),
        'password': !exists(json, 'password') ? undefined : json['password'],
        'requiresPassword': json['requiresPassword'],
        'name': json['name'],
        'fillBots': json['fillBots'],
        'enableCheats': json['enableCheats'],
        'noRunes': json['noRunes'],
        'midTowerToWin': json['midTowerToWin'],
        'midTowerKillsToWin': json['midTowerKillsToWin'],
    };
}

export function LobbyDtoToJSON(value?: LobbyDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gameMode': DotaGameModeToJSON(value.gameMode),
        'map': DotaMapToJSON(value.map),
        'patch': DotaPatchToJSON(value.patch),
        'region': RegionToJSON(value.region),
        'id': value.id,
        'owner': UserDTOToJSON(value.owner),
        'slots': ((value.slots as Array<any>).map(LobbySlotDtoToJSON)),
        'password': value.password,
        'requiresPassword': value.requiresPassword,
        'name': value.name,
        'fillBots': value.fillBots,
        'enableCheats': value.enableCheats,
        'noRunes': value.noRunes,
        'midTowerToWin': value.midTowerToWin,
        'midTowerKillsToWin': value.midTowerKillsToWin,
    };
}


