/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MaintenanceDto
 */
export interface MaintenanceDto {
    /**
     * 
     * @type {boolean}
     * @memberof MaintenanceDto
     */
    active: boolean;
}

export function MaintenanceDtoFromJSON(json: any): MaintenanceDto {
    return MaintenanceDtoFromJSONTyped(json, false);
}

export function MaintenanceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MaintenanceDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'active': json['active'],
    };
}

export function MaintenanceDtoToJSON(value?: MaintenanceDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active': value.active,
    };
}


