/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DotaGameMode,
    DotaGameModeFromJSON,
    DotaGameModeFromJSONTyped,
    DotaGameModeToJSON,
    DotaMap,
    DotaMapFromJSON,
    DotaMapFromJSONTyped,
    DotaMapToJSON,
    MatchmakingMode,
    MatchmakingModeFromJSON,
    MatchmakingModeFromJSONTyped,
    MatchmakingModeToJSON,
    QueueDurationDto,
    QueueDurationDtoFromJSON,
    QueueDurationDtoFromJSONTyped,
    QueueDurationDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface MatchmakingInfo
 */
export interface MatchmakingInfo {
    /**
     * 
     * @type {MatchmakingMode}
     * @memberof MatchmakingInfo
     */
    lobbyType: MatchmakingMode;
    /**
     * 
     * @type {DotaGameMode}
     * @memberof MatchmakingInfo
     */
    gameMode: DotaGameMode;
    /**
     * 
     * @type {DotaMap}
     * @memberof MatchmakingInfo
     */
    dotaMap: DotaMap;
    /**
     * 
     * @type {Array<QueueDurationDto>}
     * @memberof MatchmakingInfo
     */
    queueDurations: Array<QueueDurationDto>;
    /**
     * 
     * @type {boolean}
     * @memberof MatchmakingInfo
     */
    enabled: boolean;
}

export function MatchmakingInfoFromJSON(json: any): MatchmakingInfo {
    return MatchmakingInfoFromJSONTyped(json, false);
}

export function MatchmakingInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchmakingInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lobbyType': MatchmakingModeFromJSON(json['lobby_type']),
        'gameMode': DotaGameModeFromJSON(json['game_mode']),
        'dotaMap': DotaMapFromJSON(json['dota_map']),
        'queueDurations': ((json['queueDurations'] as Array<any>).map(QueueDurationDtoFromJSON)),
        'enabled': json['enabled'],
    };
}

export function MatchmakingInfoToJSON(value?: MatchmakingInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lobby_type': MatchmakingModeToJSON(value.lobbyType),
        'game_mode': DotaGameModeToJSON(value.gameMode),
        'dota_map': DotaMapToJSON(value.dotaMap),
        'queueDurations': ((value.queueDurations as Array<any>).map(QueueDurationDtoToJSON)),
        'enabled': value.enabled,
    };
}


