/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MatchReportInfoDto
 */
export interface MatchReportInfoDto {
    /**
     * 
     * @type {Array<string>}
     * @memberof MatchReportInfoDto
     */
    reportableSteamIds: Array<string>;
}

export function MatchReportInfoDtoFromJSON(json: any): MatchReportInfoDto {
    return MatchReportInfoDtoFromJSONTyped(json, false);
}

export function MatchReportInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchReportInfoDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reportableSteamIds': json['reportableSteamIds'],
    };
}

export function MatchReportInfoDtoToJSON(value?: MatchReportInfoDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reportableSteamIds': value.reportableSteamIds,
    };
}


