/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ConnectionDto,
    ConnectionDtoFromJSON,
    ConnectionDtoFromJSONTyped,
    ConnectionDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface MyProfileDto
 */
export interface MyProfileDto {
    /**
     * 
     * @type {ConnectionDto}
     * @memberof MyProfileDto
     */
    discord?: ConnectionDto;
    /**
     * 
     * @type {boolean}
     * @memberof MyProfileDto
     */
    error?: boolean;
}

export function MyProfileDtoFromJSON(json: any): MyProfileDto {
    return MyProfileDtoFromJSONTyped(json, false);
}

export function MyProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyProfileDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'discord': !exists(json, 'discord') ? undefined : ConnectionDtoFromJSON(json['discord']),
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function MyProfileDtoToJSON(value?: MyProfileDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'discord': ConnectionDtoToJSON(value.discord),
        'error': value.error,
    };
}


