/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationMatchDto
 */
export interface NotificationMatchDto {
    /**
     * 
     * @type {number}
     * @memberof NotificationMatchDto
     */
    id: number;
}

export function NotificationMatchDtoFromJSON(json: any): NotificationMatchDto {
    return NotificationMatchDtoFromJSONTyped(json, false);
}

export function NotificationMatchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationMatchDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function NotificationMatchDtoToJSON(value?: NotificationMatchDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


