/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum NotificationType {
    ACHIEVEMENTCOMPLETE = 'ACHIEVEMENT_COMPLETE',
    FEEDBACKCREATED = 'FEEDBACK_CREATED',
    TICKETCREATED = 'TICKET_CREATED',
    TICKETNEWMESSAGE = 'TICKET_NEW_MESSAGE',
    PLAYERREPORTBAN = 'PLAYER_REPORT_BAN',
    PLAYERFEEDBACK = 'PLAYER_FEEDBACK',
    REPORTCREATED = 'REPORT_CREATED',
    SUBSCRIPTIONPURCHASED = 'SUBSCRIPTION_PURCHASED',
    ITEMDROPPED = 'ITEM_DROPPED',
    TRADEOFFEREXPIRED = 'TRADE_OFFER_EXPIRED'
}

export function NotificationTypeFromJSON(json: any): NotificationType {
    return NotificationTypeFromJSONTyped(json, false);
}

export function NotificationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationType {
    return json as NotificationType;
}

export function NotificationTypeToJSON(value?: NotificationType | null): any {
    return value as any;
}

