/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  UserDTO,
  UserDTOFromJSON,
  UserDTOFromJSONTyped,
  UserDTOToJSON,
} from "./";

/**
 * 
 * @export
 * @interface PartyDto
 */
export interface PartyDto {
  /**
   *
   * @type {string}
   * @memberof PartyDto
   */
  id: string;
  /**
   *
   * @type {UserDTO}
   * @memberof PartyDto
   */
  leader: UserDTO;
  /**
   *
   * @type {Array<UserDTO>}
   * @memberof PartyDto
   */
  players: Array<UserDTO>;
}

export function PartyDtoFromJSON(json: any): PartyDto {
  return PartyDtoFromJSONTyped(json, false);
}

export function PartyDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PartyDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    leader: UserDTOFromJSON(json["leader"]),
    players: (json["players"] as Array<any>).map(UserDTOFromJSON),
  };
}

export function PartyDtoToJSON(value?: PartyDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    leader: UserDTOToJSON(value.leader),
    players: (value.players as Array<any>).map(UserDTOToJSON),
  };
}


