/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PlayerTeammateDto
 */
export interface PlayerTeammateDto {
  /**
   *
   * @type {string}
   * @memberof PlayerTeammateDto
   */
  steamId: string;
  /**
   *
   * @type {string}
   * @memberof PlayerTeammateDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof PlayerTeammateDto
   */
  avatar: string;
  /**
   *
   * @type {number}
   * @memberof PlayerTeammateDto
   */
  games: number;
  /**
   *
   * @type {number}
   * @memberof PlayerTeammateDto
   */
  wins: number;
  /**
   *
   * @type {number}
   * @memberof PlayerTeammateDto
   */
  losses: number;
  /**
   *
   * @type {number}
   * @memberof PlayerTeammateDto
   */
  winrate: number;
  /**
   *
   * @type {number}
   * @memberof PlayerTeammateDto
   */
  rank: number;
}

export function PlayerTeammateDtoFromJSON(json: any): PlayerTeammateDto {
  return PlayerTeammateDtoFromJSONTyped(json, false);
}

export function PlayerTeammateDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlayerTeammateDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    steamId: json["steam_id"],
    name: json["name"],
    avatar: json["avatar"],
    games: json["games"],
    wins: json["wins"],
    losses: json["losses"],
    winrate: json["winrate"],
    rank: json["rank"],
  };
}

export function PlayerTeammateDtoToJSON(value?: PlayerTeammateDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    steam_id: value.steamId,
    name: value.name,
    avatar: value.avatar,
    games: value.games,
    wins: value.wins,
    losses: value.losses,
    winrate: value.winrate,
    rank: value.rank,
  };
}
