/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GamemodeAccessMap,
    GamemodeAccessMapFromJSON,
    GamemodeAccessMapFromJSONTyped,
    GamemodeAccessMapToJSON,
    PlayerAspectDto,
    PlayerAspectDtoFromJSON,
    PlayerAspectDtoFromJSONTyped,
    PlayerAspectDtoToJSON,
    PlayerStatsDto,
    PlayerStatsDtoFromJSON,
    PlayerStatsDtoFromJSONTyped,
    PlayerStatsDtoToJSON,
    UserDTO,
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface PlayerSummaryDto
 */
export interface PlayerSummaryDto {
    /**
     * 
     * @type {UserDTO}
     * @memberof PlayerSummaryDto
     */
    user: UserDTO;
    /**
     * 
     * @type {string}
     * @memberof PlayerSummaryDto
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof PlayerSummaryDto
     */
    calibrationGamesLeft: number;
    /**
     * 
     * @type {PlayerStatsDto}
     * @memberof PlayerSummaryDto
     */
    seasonStats: PlayerStatsDto;
    /**
     * 
     * @type {PlayerStatsDto}
     * @memberof PlayerSummaryDto
     */
    overallStats: PlayerStatsDto;
    /**
     * 
     * @type {GamemodeAccessMap}
     * @memberof PlayerSummaryDto
     */
    accessMap: GamemodeAccessMap;
    /**
     * 
     * @type {Array<PlayerAspectDto>}
     * @memberof PlayerSummaryDto
     */
    aspects: Array<PlayerAspectDto>;
}

export function PlayerSummaryDtoFromJSON(json: any): PlayerSummaryDto {
    return PlayerSummaryDtoFromJSONTyped(json, false);
}

export function PlayerSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerSummaryDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserDTOFromJSON(json['user']),
        'id': json['id'],
        'calibrationGamesLeft': json['calibrationGamesLeft'],
        'seasonStats': PlayerStatsDtoFromJSON(json['seasonStats']),
        'overallStats': PlayerStatsDtoFromJSON(json['overallStats']),
        'accessMap': GamemodeAccessMapFromJSON(json['accessMap']),
        'aspects': ((json['aspects'] as Array<any>).map(PlayerAspectDtoFromJSON)),
    };
}

export function PlayerSummaryDtoToJSON(value?: PlayerSummaryDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserDTOToJSON(value.user),
        'id': value.id,
        'calibrationGamesLeft': value.calibrationGamesLeft,
        'seasonStats': PlayerStatsDtoToJSON(value.seasonStats),
        'overallStats': PlayerStatsDtoToJSON(value.overallStats),
        'accessMap': GamemodeAccessMapToJSON(value.accessMap),
        'aspects': ((value.aspects as Array<any>).map(PlayerAspectDtoToJSON)),
    };
}


