/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PlayerFeedbackDto,
    PlayerFeedbackDtoFromJSON,
    PlayerFeedbackDtoFromJSONTyped,
    PlayerFeedbackDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface PlayerFeedbackPageDto
 */
export interface PlayerFeedbackPageDto {
    /**
     * 
     * @type {number}
     * @memberof PlayerFeedbackPageDto
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerFeedbackPageDto
     */
    pages: number;
    /**
     * 
     * @type {number}
     * @memberof PlayerFeedbackPageDto
     */
    perPage: number;
    /**
     * 
     * @type {Array<PlayerFeedbackDto>}
     * @memberof PlayerFeedbackPageDto
     */
    data: Array<PlayerFeedbackDto>;
}

export function PlayerFeedbackPageDtoFromJSON(json: any): PlayerFeedbackPageDto {
    return PlayerFeedbackPageDtoFromJSONTyped(json, false);
}

export function PlayerFeedbackPageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerFeedbackPageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pages': json['pages'],
        'perPage': json['perPage'],
        'data': ((json['data'] as Array<any>).map(PlayerFeedbackDtoFromJSON)),
    };
}

export function PlayerFeedbackPageDtoToJSON(value?: PlayerFeedbackPageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pages': value.pages,
        'perPage': value.perPage,
        'data': ((value.data as Array<any>).map(PlayerFeedbackDtoToJSON)),
    };
}


