/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PurchaseWithTradeBalanceDto
 */
export interface PurchaseWithTradeBalanceDto {
    /**
     * 
     * @type {number}
     * @memberof PurchaseWithTradeBalanceDto
     */
    productId: number;
}

export function PurchaseWithTradeBalanceDtoFromJSON(json: any): PurchaseWithTradeBalanceDto {
    return PurchaseWithTradeBalanceDtoFromJSONTyped(json, false);
}

export function PurchaseWithTradeBalanceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PurchaseWithTradeBalanceDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productId': json['productId'],
    };
}

export function PurchaseWithTradeBalanceDtoToJSON(value?: PurchaseWithTradeBalanceDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'productId': value.productId,
    };
}


