/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueueDurationDto
 */
export interface QueueDurationDto {
    /**
     * 
     * @type {number}
     * @memberof QueueDurationDto
     */
    utcHour: number;
    /**
     * 
     * @type {number}
     * @memberof QueueDurationDto
     */
    duration?: number;
}

export function QueueDurationDtoFromJSON(json: any): QueueDurationDto {
    return QueueDurationDtoFromJSONTyped(json, false);
}

export function QueueDurationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueueDurationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'utcHour': json['utcHour'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
    };
}

export function QueueDurationDtoToJSON(value?: QueueDurationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'utcHour': value.utcHour,
        'duration': value.duration,
    };
}


