/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecalibrationDto
 */
export interface RecalibrationDto {
    /**
     * 
     * @type {number}
     * @memberof RecalibrationDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof RecalibrationDto
     */
    createdAt: string;
    /**
     * 
     * @type {number}
     * @memberof RecalibrationDto
     */
    seasonId: number;
}

export function RecalibrationDtoFromJSON(json: any): RecalibrationDto {
    return RecalibrationDtoFromJSONTyped(json, false);
}

export function RecalibrationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecalibrationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': json['createdAt'],
        'seasonId': json['seasonId'],
    };
}

export function RecalibrationDtoToJSON(value?: RecalibrationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt,
        'seasonId': value.seasonId,
    };
}


