/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReportPlayerInMatchDto
 */
export interface ReportPlayerInMatchDto {
    /**
     * 
     * @type {string}
     * @memberof ReportPlayerInMatchDto
     */
    steamId: string;
    /**
     * 
     * @type {number}
     * @memberof ReportPlayerInMatchDto
     */
    matchId: number;
    /**
     * 
     * @type {number}
     * @memberof ReportPlayerInMatchDto
     */
    ruleId: number;
    /**
     * 
     * @type {string}
     * @memberof ReportPlayerInMatchDto
     */
    comment: string;
}

export function ReportPlayerInMatchDtoFromJSON(json: any): ReportPlayerInMatchDto {
    return ReportPlayerInMatchDtoFromJSONTyped(json, false);
}

export function ReportPlayerInMatchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportPlayerInMatchDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'steamId': json['steamId'],
        'matchId': json['matchId'],
        'ruleId': json['ruleId'],
        'comment': json['comment'],
    };
}

export function ReportPlayerInMatchDtoToJSON(value?: ReportPlayerInMatchDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'steamId': value.steamId,
        'matchId': value.matchId,
        'ruleId': value.ruleId,
        'comment': value.comment,
    };
}


