/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResetGameDataDto
 */
export interface ResetGameDataDto {
    /**
     * 
     * @type {string}
     * @memberof ResetGameDataDto
     */
    gameId: string;
}

export function ResetGameDataDtoFromJSON(json: any): ResetGameDataDto {
    return ResetGameDataDtoFromJSONTyped(json, false);
}

export function ResetGameDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResetGameDataDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gameId': json['gameId'],
    };
}

export function ResetGameDataDtoToJSON(value?: ResetGameDataDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gameId': value.gameId,
    };
}


