/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RulePunishmentDto,
    RulePunishmentDtoFromJSON,
    RulePunishmentDtoFromJSONTyped,
    RulePunishmentDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface RuleDto
 */
export interface RuleDto {
    /**
     * 
     * @type {string}
     * @memberof RuleDto
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof RuleDto
     */
    index: number;
    /**
     * 
     * @type {string}
     * @memberof RuleDto
     */
    title: string;
    /**
     * 
     * @type {boolean}
     * @memberof RuleDto
     */
    automatic: boolean;
    /**
     * 
     * @type {string}
     * @memberof RuleDto
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof RuleDto
     */
    parentId?: number;
    /**
     * 
     * @type {Array<RuleDto>}
     * @memberof RuleDto
     */
    children: Array<RuleDto>;
    /**
     * 
     * @type {RulePunishmentDto}
     * @memberof RuleDto
     */
    punishment?: RulePunishmentDto;
}

export function RuleDtoFromJSON(json: any): RuleDto {
    return RuleDtoFromJSONTyped(json, false);
}

export function RuleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuleDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'index': json['index'],
        'title': json['title'],
        'automatic': json['automatic'],
        'description': json['description'],
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
        'children': ((json['children'] as Array<any>).map(RuleDtoFromJSON)),
        'punishment': !exists(json, 'punishment') ? undefined : RulePunishmentDtoFromJSON(json['punishment']),
    };
}

export function RuleDtoToJSON(value?: RuleDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'index': value.index,
        'title': value.title,
        'automatic': value.automatic,
        'description': value.description,
        'parentId': value.parentId,
        'children': ((value.children as Array<any>).map(RuleDtoToJSON)),
        'punishment': RulePunishmentDtoToJSON(value.punishment),
    };
}


