/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunRconResponseDto
 */
export interface RunRconResponseDto {
    /**
     * 
     * @type {string}
     * @memberof RunRconResponseDto
     */
    response: string;
}

export function RunRconResponseDtoFromJSON(json: any): RunRconResponseDto {
    return RunRconResponseDtoFromJSONTyped(json, false);
}

export function RunRconResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunRconResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': json['response'],
    };
}

export function RunRconResponseDtoToJSON(value?: RunRconResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': value.response,
    };
}


