/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunRconDto
 */
export interface RunRconDto {
    /**
     * 
     * @type {string}
     * @memberof RunRconDto
     */
    serverUrl: string;
    /**
     * 
     * @type {string}
     * @memberof RunRconDto
     */
    command: string;
}

export function RunRconDtoFromJSON(json: any): RunRconDto {
    return RunRconDtoFromJSONTyped(json, false);
}

export function RunRconDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunRconDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'serverUrl': json['serverUrl'],
        'command': json['command'],
    };
}

export function RunRconDtoToJSON(value?: RunRconDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'serverUrl': value.serverUrl,
        'command': value.command,
    };
}


