/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduleStrategy
 */
export interface ScheduleStrategy {
    /**
     * 
     * @type {number}
     * @memberof ScheduleStrategy
     */
    gameDurationSeconds: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduleStrategy
     */
    gameBreakDurationSeconds: number;
}

export function ScheduleStrategyFromJSON(json: any): ScheduleStrategy {
    return ScheduleStrategyFromJSONTyped(json, false);
}

export function ScheduleStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleStrategy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gameDurationSeconds': json['gameDurationSeconds'],
        'gameBreakDurationSeconds': json['gameBreakDurationSeconds'],
    };
}

export function ScheduleStrategyToJSON(value?: ScheduleStrategy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gameDurationSeconds': value.gameDurationSeconds,
        'gameBreakDurationSeconds': value.gameBreakDurationSeconds,
    };
}


