/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreatePaymentItemDto,
    CreatePaymentItemDtoFromJSON,
    CreatePaymentItemDtoFromJSONTyped,
    CreatePaymentItemDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface SelfCreatePaymentDto
 */
export interface SelfCreatePaymentDto {
    /**
     * 
     * @type {number}
     * @memberof SelfCreatePaymentDto
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof SelfCreatePaymentDto
     */
    orderId: string;
    /**
     * 
     * @type {Array<CreatePaymentItemDto>}
     * @memberof SelfCreatePaymentDto
     */
    info: Array<CreatePaymentItemDto>;
    /**
     * 
     * @type {string}
     * @memberof SelfCreatePaymentDto
     */
    signature: string;
}

export function SelfCreatePaymentDtoFromJSON(json: any): SelfCreatePaymentDto {
    return SelfCreatePaymentDtoFromJSONTyped(json, false);
}

export function SelfCreatePaymentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SelfCreatePaymentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'orderId': json['order_id'],
        'info': ((json['info'] as Array<any>).map(CreatePaymentItemDtoFromJSON)),
        'signature': json['signature'],
    };
}

export function SelfCreatePaymentDtoToJSON(value?: SelfCreatePaymentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'order_id': value.orderId,
        'info': ((value.info as Array<any>).map(CreatePaymentItemDtoToJSON)),
        'signature': value.signature,
    };
}


