/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MatchmakingMode,
    MatchmakingModeFromJSON,
    MatchmakingModeFromJSONTyped,
    MatchmakingModeToJSON,
} from './';

/**
 * 
 * @export
 * @interface SessionDto
 */
export interface SessionDto {
    /**
     * 
     * @type {MatchmakingMode}
     * @memberof SessionDto
     */
    lobbyType: MatchmakingMode;
    /**
     * 
     * @type {string}
     * @memberof SessionDto
     */
    serverUrl: string;
    /**
     * 
     * @type {number}
     * @memberof SessionDto
     */
    matchId: number;
}

export function SessionDtoFromJSON(json: any): SessionDto {
    return SessionDtoFromJSONTyped(json, false);
}

export function SessionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lobbyType': MatchmakingModeFromJSON(json['lobbyType']),
        'serverUrl': json['serverUrl'],
        'matchId': json['matchId'],
    };
}

export function SessionDtoToJSON(value?: SessionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lobbyType': MatchmakingModeToJSON(value.lobbyType),
        'serverUrl': value.serverUrl,
        'matchId': value.matchId,
    };
}


