/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimulatePaymentDto
 */
export interface SimulatePaymentDto {
    /**
     * 
     * @type {number}
     * @memberof SimulatePaymentDto
     */
    productId: number;
    /**
     * 
     * @type {string}
     * @memberof SimulatePaymentDto
     */
    steamId: string;
    /**
     * 
     * @type {string}
     * @memberof SimulatePaymentDto
     */
    paymentId: string;
}

export function SimulatePaymentDtoFromJSON(json: any): SimulatePaymentDto {
    return SimulatePaymentDtoFromJSONTyped(json, false);
}

export function SimulatePaymentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulatePaymentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productId': json['productId'],
        'steamId': json['steamId'],
        'paymentId': json['paymentId'],
    };
}

export function SimulatePaymentDtoToJSON(value?: SimulatePaymentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'productId': value.productId,
        'steamId': value.steamId,
        'paymentId': value.paymentId,
    };
}


