/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreHatItemDto
 */
export interface StoreHatItemDto {
    /**
     * 
     * @type {string}
     * @memberof StoreHatItemDto
     */
    imageKey: string;
}

export function StoreHatItemDtoFromJSON(json: any): StoreHatItemDto {
    return StoreHatItemDtoFromJSONTyped(json, false);
}

export function StoreHatItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreHatItemDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imageKey': json['imageKey'],
    };
}

export function StoreHatItemDtoToJSON(value?: StoreHatItemDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'imageKey': value.imageKey,
    };
}


