/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionDtoKeys
 */
export interface SubscriptionDtoKeys {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionDtoKeys
     */
    p256dh?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionDtoKeys
     */
    auth?: string;
}

export function SubscriptionDtoKeysFromJSON(json: any): SubscriptionDtoKeys {
    return SubscriptionDtoKeysFromJSONTyped(json, false);
}

export function SubscriptionDtoKeysFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionDtoKeys {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'p256dh': !exists(json, 'p256dh') ? undefined : json['p256dh'],
        'auth': !exists(json, 'auth') ? undefined : json['auth'],
    };
}

export function SubscriptionDtoKeysToJSON(value?: SubscriptionDtoKeys | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'p256dh': value.p256dh,
        'auth': value.auth,
    };
}


