/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SubscriptionDtoKeys,
    SubscriptionDtoKeysFromJSON,
    SubscriptionDtoKeysFromJSONTyped,
    SubscriptionDtoKeysToJSON,
} from './';

/**
 * 
 * @export
 * @interface SubscriptionDto
 */
export interface SubscriptionDto {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionDto
     */
    endpoint: string;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionDto
     */
    expirationTime: number | null;
    /**
     * 
     * @type {SubscriptionDtoKeys}
     * @memberof SubscriptionDto
     */
    keys: SubscriptionDtoKeys;
}

export function SubscriptionDtoFromJSON(json: any): SubscriptionDto {
    return SubscriptionDtoFromJSONTyped(json, false);
}

export function SubscriptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'endpoint': json['endpoint'],
        'expirationTime': json['expirationTime'],
        'keys': SubscriptionDtoKeysFromJSON(json['keys']),
    };
}

export function SubscriptionDtoToJSON(value?: SubscriptionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'endpoint': value.endpoint,
        'expirationTime': value.expirationTime,
        'keys': SubscriptionDtoKeysToJSON(value.keys),
    };
}


