/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ThreadMessageDTO,
    ThreadMessageDTOFromJSON,
    ThreadMessageDTOFromJSONTyped,
    ThreadMessageDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface ThreadMessagePageDTO
 */
export interface ThreadMessagePageDTO {
    /**
     * 
     * @type {Array<ThreadMessageDTO>}
     * @memberof ThreadMessagePageDTO
     */
    data: Array<ThreadMessageDTO>;
    /**
     * 
     * @type {number}
     * @memberof ThreadMessagePageDTO
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ThreadMessagePageDTO
     */
    perPage: number;
    /**
     * 
     * @type {number}
     * @memberof ThreadMessagePageDTO
     */
    pages: number;
    /**
     * 
     * @type {string}
     * @memberof ThreadMessagePageDTO
     */
    cursor?: string;
}

export function ThreadMessagePageDTOFromJSON(json: any): ThreadMessagePageDTO {
    return ThreadMessagePageDTOFromJSONTyped(json, false);
}

export function ThreadMessagePageDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadMessagePageDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ThreadMessageDTOFromJSON)),
        'page': json['page'],
        'perPage': json['perPage'],
        'pages': json['pages'],
        'cursor': !exists(json, 'cursor') ? undefined : json['cursor'],
    };
}

export function ThreadMessagePageDTOToJSON(value?: ThreadMessagePageDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ThreadMessageDTOToJSON)),
        'page': value.page,
        'perPage': value.perPage,
        'pages': value.pages,
        'cursor': value.cursor,
    };
}


