/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {ThreadDTO, ThreadDTOFromJSON, ThreadDTOToJSON,} from "./";

/**
 *
 * @export
 * @interface ThreadPageDTO
 */
export interface ThreadPageDTO {
  /**
   *
   * @type {Array<ThreadDTO>}
   * @memberof ThreadPageDTO
   */
  data: Array<ThreadDTO>;
  /**
   *
   * @type {number}
   * @memberof ThreadPageDTO
   */
  page: number;
  /**
   *
   * @type {number}
   * @memberof ThreadPageDTO
   */
  perPage: number;
  /**
   *
   * @type {number}
   * @memberof ThreadPageDTO
   */
  pages: number;
}

export function ThreadPageDTOFromJSON(json: any): ThreadPageDTO {
  return ThreadPageDTOFromJSONTyped(json, false);
}

export function ThreadPageDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ThreadPageDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    data: (json["data"] as Array<any>).map(ThreadDTOFromJSON),
    page: json["page"],
    perPage: json["perPage"],
    pages: json["pages"],
  };
}

export function ThreadPageDTOToJSON(value?: ThreadPageDTO | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    data: (value.data as Array<any>).map(ThreadDTOToJSON),
    page: value.page,
    perPage: value.perPage,
    pages: value.pages,
  };
}
