/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BestOfStrategy,
    BestOfStrategyFromJSON,
    BestOfStrategyFromJSONTyped,
    BestOfStrategyToJSON,
    BracketType,
    BracketTypeFromJSON,
    BracketTypeFromJSONTyped,
    BracketTypeToJSON,
    DotaGameMode,
    DotaGameModeFromJSON,
    DotaGameModeFromJSONTyped,
    DotaGameModeToJSON,
    RegistrationDto,
    RegistrationDtoFromJSON,
    RegistrationDtoFromJSONTyped,
    RegistrationDtoToJSON,
    ScheduleStrategy,
    ScheduleStrategyFromJSON,
    ScheduleStrategyFromJSONTyped,
    ScheduleStrategyToJSON,
    TournamentStatus,
    TournamentStatusFromJSON,
    TournamentStatusFromJSONTyped,
    TournamentStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface TournamentDto
 */
export interface TournamentDto {
    /**
     * 
     * @type {TournamentStatus}
     * @memberof TournamentDto
     */
    status: TournamentStatus;
    /**
     * 
     * @type {BracketType}
     * @memberof TournamentDto
     */
    strategy: BracketType;
    /**
     * 
     * @type {DotaGameMode}
     * @memberof TournamentDto
     */
    gameMode: DotaGameMode;
    /**
     * 
     * @type {number}
     * @memberof TournamentDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof TournamentDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentDto
     */
    imageUrl: string;
    /**
     * 
     * @type {number}
     * @memberof TournamentDto
     */
    teamSize: number;
    /**
     * 
     * @type {BestOfStrategy}
     * @memberof TournamentDto
     */
    bestOfConfig: BestOfStrategy;
    /**
     * 
     * @type {string}
     * @memberof TournamentDto
     */
    startDate: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentDto
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof TournamentDto
     */
    prize: string;
    /**
     * 
     * @type {Array<RegistrationDto>}
     * @memberof TournamentDto
     */
    registrations: Array<RegistrationDto>;
    /**
     * 
     * @type {ScheduleStrategy}
     * @memberof TournamentDto
     */
    scheduleStrategy: ScheduleStrategy;
}

export function TournamentDtoFromJSON(json: any): TournamentDto {
    return TournamentDtoFromJSONTyped(json, false);
}

export function TournamentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': TournamentStatusFromJSON(json['status']),
        'strategy': BracketTypeFromJSON(json['strategy']),
        'gameMode': DotaGameModeFromJSON(json['gameMode']),
        'id': json['id'],
        'name': json['name'],
        'imageUrl': json['imageUrl'],
        'teamSize': json['teamSize'],
        'bestOfConfig': BestOfStrategyFromJSON(json['bestOfConfig']),
        'startDate': json['startDate'],
        'description': json['description'],
        'prize': json['prize'],
        'registrations': ((json['registrations'] as Array<any>).map(RegistrationDtoFromJSON)),
        'scheduleStrategy': ScheduleStrategyFromJSON(json['scheduleStrategy']),
    };
}

export function TournamentDtoToJSON(value?: TournamentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': TournamentStatusToJSON(value.status),
        'strategy': BracketTypeToJSON(value.strategy),
        'gameMode': DotaGameModeToJSON(value.gameMode),
        'id': value.id,
        'name': value.name,
        'imageUrl': value.imageUrl,
        'teamSize': value.teamSize,
        'bestOfConfig': BestOfStrategyToJSON(value.bestOfConfig),
        'startDate': value.startDate,
        'description': value.description,
        'prize': value.prize,
        'registrations': ((value.registrations as Array<any>).map(RegistrationDtoToJSON)),
        'scheduleStrategy': ScheduleStrategyToJSON(value.scheduleStrategy),
    };
}


