/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TournamentStatus {
    DRAFT = 'DRAFT',
    REGISTRATION = 'REGISTRATION',
    READYCHECK = 'READY_CHECK',
    INPROGRESS = 'IN_PROGRESS',
    FINISHED = 'FINISHED'
}

export function TournamentStatusFromJSON(json: any): TournamentStatus {
    return TournamentStatusFromJSONTyped(json, false);
}

export function TournamentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): TournamentStatus {
    return json as TournamentStatus;
}

export function TournamentStatusToJSON(value?: TournamentStatus | null): any {
    return value as any;
}

