/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTradeLinkDto
 */
export interface UpdateTradeLinkDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateTradeLinkDto
     */
    tradeUrl: string;
}

export function UpdateTradeLinkDtoFromJSON(json: any): UpdateTradeLinkDto {
    return UpdateTradeLinkDtoFromJSONTyped(json, false);
}

export function UpdateTradeLinkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTradeLinkDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tradeUrl': json['tradeUrl'],
    };
}

export function UpdateTradeLinkDtoToJSON(value?: UpdateTradeLinkDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tradeUrl': value.tradeUrl,
    };
}


