/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {Role, RoleFromJSON, RoleToJSON} from "./";

/**
 *
 * @export
 * @interface UpdateRolesDto
 */
export interface UpdateRolesDto {
  /**
   *
   * @type {Role}
   * @memberof UpdateRolesDto
   */
  role: Role;
  /**
   *
   * @type {string}
   * @memberof UpdateRolesDto
   */
  steamId: string;
  /**
   *
   * @type {number}
   * @memberof UpdateRolesDto
   */
  endTime: number;
}

export function UpdateRolesDtoFromJSON(json: any): UpdateRolesDto {
    return UpdateRolesDtoFromJSONTyped(json, false);
}

export function UpdateRolesDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRolesDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
      role: RoleFromJSON(json["role"]),
      steamId: json["steam_id"],
      endTime: json["end_time"],
    };
}

export function UpdateRolesDtoToJSON(value?: UpdateRolesDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
      role: RoleToJSON(value.role),
      steam_id: value.steamId,
      end_time: value.endTime,
    };
}


