/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateThreadDTO
 */
export interface UpdateThreadDTO {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateThreadDTO
     */
    pinned: boolean;
}

export function UpdateThreadDTOFromJSON(json: any): UpdateThreadDTO {
    return UpdateThreadDTOFromJSONTyped(json, false);
}

export function UpdateThreadDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateThreadDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pinned': json['pinned'],
    };
}

export function UpdateThreadDTOToJSON(value?: UpdateThreadDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pinned': value.pinned,
    };
}


