/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Dota2Version,
    Dota2VersionFromJSON,
    Dota2VersionFromJSONTyped,
    Dota2VersionToJSON,
    MatchmakingMode,
    MatchmakingModeFromJSON,
    MatchmakingModeFromJSONTyped,
    MatchmakingModeToJSON,
} from './';

/**
 * 
 * @export
 * @interface UpdateModeDTO
 */
export interface UpdateModeDTO {
    /**
     * 
     * @type {MatchmakingMode}
     * @memberof UpdateModeDTO
     */
    mode: MatchmakingMode;
    /**
     * 
     * @type {Dota2Version}
     * @memberof UpdateModeDTO
     */
    version: Dota2Version;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateModeDTO
     */
    enabled: boolean;
}

export function UpdateModeDTOFromJSON(json: any): UpdateModeDTO {
    return UpdateModeDTOFromJSONTyped(json, false);
}

export function UpdateModeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateModeDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mode': MatchmakingModeFromJSON(json['mode']),
        'version': Dota2VersionFromJSON(json['version']),
        'enabled': json['enabled'],
    };
}

export function UpdateModeDTOToJSON(value?: UpdateModeDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mode': MatchmakingModeToJSON(value.mode),
        'version': Dota2VersionToJSON(value.version),
        'enabled': value.enabled,
    };
}


