/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRuleDto
 */
export interface UpdateRuleDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateRuleDto
     */
    parent?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateRuleDto
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateRuleDto
     */
    index?: number;
}

export function UpdateRuleDtoFromJSON(json: any): UpdateRuleDto {
    return UpdateRuleDtoFromJSONTyped(json, false);
}

export function UpdateRuleDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRuleDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parent': !exists(json, 'parent') ? undefined : json['parent'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'index': !exists(json, 'index') ? undefined : json['index'],
    };
}

export function UpdateRuleDtoToJSON(value?: UpdateRuleDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent': value.parent,
        'description': value.description,
        'index': value.index,
    };
}


