/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UploadedImageDto,
    UploadedImageDtoFromJSON,
    UploadedImageDtoFromJSONTyped,
    UploadedImageDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface UploadedImagePageDto
 */
export interface UploadedImagePageDto {
    /**
     * 
     * @type {Array<UploadedImageDto>}
     * @memberof UploadedImagePageDto
     */
    items: Array<UploadedImageDto>;
    /**
     * 
     * @type {string}
     * @memberof UploadedImagePageDto
     */
    ctoken?: string;
}

export function UploadedImagePageDtoFromJSON(json: any): UploadedImagePageDto {
    return UploadedImagePageDtoFromJSONTyped(json, false);
}

export function UploadedImagePageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadedImagePageDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(UploadedImageDtoFromJSON)),
        'ctoken': !exists(json, 'ctoken') ? undefined : json['ctoken'],
    };
}

export function UploadedImagePageDtoToJSON(value?: UploadedImagePageDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(UploadedImageDtoToJSON)),
        'ctoken': value.ctoken,
    };
}


