/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserDTO
 */
export interface UserDTO {
  /**
   *
   * @type {string}
   * @memberof UserDTO
   */
  steamId: string;
  /**
   *
   * @type {string}
   * @memberof UserDTO
   */
  avatar: string;
  /**
   *
   * @type {string}
   * @memberof UserDTO
   */
  name: string;
}

export function UserDTOFromJSON(json: any): UserDTO {
  return UserDTOFromJSONTyped(json, false);
}

export function UserDTOFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserDTO {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    steamId: json["steamId"],
    avatar: json["avatar"],
    name: json["name"],
  };
}

export function UserDTOToJSON(value?: UserDTO | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    steamId: value.steamId,
    avatar: value.avatar,
    name: value.name,
  };
}


