/* tslint:disable */
/* eslint-disable */
/**
 * Public REST api for dota2classic
 * All stuff
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserConnectionDto
 */
export interface UserConnectionDto {
    /**
     * 
     * @type {string}
     * @memberof UserConnectionDto
     */
    connection: UserConnectionDtoConnectionEnum;
    /**
     * 
     * @type {string}
     * @memberof UserConnectionDto
     */
    externalId: string;
}

export function UserConnectionDtoFromJSON(json: any): UserConnectionDto {
    return UserConnectionDtoFromJSONTyped(json, false);
}

export function UserConnectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserConnectionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'connection': json['connection'],
        'externalId': json['externalId'],
    };
}

export function UserConnectionDtoToJSON(value?: UserConnectionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'connection': value.connection,
        'externalId': value.externalId,
    };
}

/**
* @export
* @enum {string}
*/
export enum UserConnectionDtoConnectionEnum {
    DISCORD = 'DISCORD',
    TWITCH = 'TWITCH'
}


