export default [
  { tag: "npc_dota_hero_shadow_shaman", name: "Shadow Shaman" },
  { tag: "npc_dota_hero_beastmaster", name: "Beastmaster" },
  { tag: "npc_dota_hero_nevermore", name: "Shadow Fiend" },
  { tag: "npc_dota_hero_lion", name: "Lion" },
  { tag: "npc_dota_hero_drow_ranger", name: "Drow Ranger" },
  { tag: "npc_dota_hero_ancient_apparition", name: "Ancient Apparition" },
  { tag: "npc_dota_hero_doom_bringer", name: "Doom" },
  { tag: "npc_dota_hero_bane", name: "Bane" },
  { tag: "npc_dota_hero_dazzle", name: "Dazzle" },
  { tag: "npc_dota_hero_crystal_maiden", name: "Crystal Maiden" },
  { tag: "npc_dota_hero_night_stalker", name: "Night Stalker" },
  { tag: "npc_dota_hero_dragon_knight", name: "Dragon Knight" },
  { tag: "npc_dota_hero_rattletrap", name: "Clockwerk" },
  { tag: "npc_dota_hero_faceless_void", name: "Faceless Void" },
  { tag: "npc_dota_hero_venomancer", name: "Venomancer" },
  { tag: "npc_dota_hero_necrolyte", name: "Necrophos" },
  { tag: "npc_dota_hero_tiny", name: "Tiny" },
  { tag: "npc_dota_hero_tinker", name: "Tinker" },
  { tag: "npc_dota_hero_leshrac", name: "Leshrac" },
  { tag: "npc_dota_hero_lich", name: "Lich" },
  { tag: "npc_dota_hero_slardar", name: "Slardar" },
  { tag: "npc_dota_hero_sand_king", name: "Sand King" },
  { tag: "npc_dota_hero_lina", name: "Lina" },
  { tag: "npc_dota_hero_mirana", name: "Mirana" },
  { tag: "npc_dota_hero_enigma", name: "Enigma" },
  { tag: "npc_dota_hero_spectre", name: "Spectre" },
  { tag: "npc_dota_hero_sniper", name: "Sniper" },
  { tag: "npc_dota_hero_enchantress", name: "Enchantress" },
  { tag: "npc_dota_hero_pudge", name: "Pudge" },
  { tag: "npc_dota_hero_razor", name: "Razor" },
  { tag: "npc_dota_hero_puck", name: "Puck" },
  { tag: "npc_dota_hero_life_stealer", name: "Lifestealer" },
  { tag: "npc_dota_hero_kunkka", name: "Kunkka" },
  { tag: "npc_dota_hero_morphling", name: "Morphling" },
  { tag: "npc_dota_hero_sven", name: "Sven" },
  { tag: "npc_dota_hero_vengefulspirit", name: "Vengeful Spirit" },
  { tag: "npc_dota_hero_furion", name: "Nature's Prophet" },
  { tag: "npc_dota_hero_riki", name: "Riki" },
  { tag: "npc_dota_hero_antimage", name: "Anti-Mage" },
  { tag: "npc_dota_hero_earthshaker", name: "Earthshaker" },
  { tag: "npc_dota_hero_dark_seer", name: "Dark Seer" },
  { tag: "npc_dota_hero_juggernaut", name: "Juggernaut" },
  { tag: "npc_dota_hero_bloodseeker", name: "Bloodseeker" },
  { tag: "npc_dota_hero_viper", name: "Viper" },
  { tag: "npc_dota_hero_chen", name: "Chen" },
  { tag: "npc_dota_hero_tidehunter", name: "Tidehunter" },
  { tag: "npc_dota_hero_omniknight", name: "Omniknight" },
  { tag: "npc_dota_hero_pugna", name: "Pugna" },
  { tag: "npc_dota_hero_axe", name: "Axe" },
  { tag: "npc_dota_hero_storm_spirit", name: "Storm Spirit" },
  { tag: "npc_dota_hero_invoker", name: "Invoker" },
  { tag: "npc_dota_hero_lycan", name: "Lycan" },
  { tag: "npc_dota_hero_brewmaster", name: "Brewmaster" },
  { tag: "npc_dota_hero_weaver", name: "Weaver" },
  { tag: "npc_dota_hero_alchemist", name: "Alchemist" },
  { tag: "npc_dota_hero_chaos_knight", name: "Chaos Knight" },
  { tag: "npc_dota_hero_ogre_magi", name: "Ogre Magi" },
  { tag: "npc_dota_hero_skeleton_king", name: "Wraith King" },
  { tag: "npc_dota_hero_broodmother", name: "Broodmother" },
  { tag: "npc_dota_hero_lone_druid", name: "Lone Druid" },
  { tag: "npc_dota_hero_clinkz", name: "Clinkz" },
  { tag: "npc_dota_hero_witch_doctor", name: "Witch Doctor" },
  { tag: "npc_dota_hero_windrunner", name: "Windranger" },
  { tag: "npc_dota_hero_warlock", name: "Warlock" },
  { tag: "npc_dota_hero_silencer", name: "Silencer" },
  { tag: "npc_dota_hero_phantom_lancer", name: "Phantom Lancer" },
  { tag: "npc_dota_hero_shadow_demon", name: "Shadow Demon" },
  { tag: "npc_dota_hero_obsidian_destroyer", name: "Outworld Devourer" },
  { tag: "npc_dota_hero_death_prophet", name: "Death Prophet" },
  { tag: "npc_dota_hero_queenofpain", name: "Queen of Pain" },
  { tag: "npc_dota_hero_spirit_breaker", name: "Spirit Breaker" },
  { tag: "npc_dota_hero_ursa", name: "Ursa" },
  { tag: "npc_dota_hero_huskar", name: "Huskar" },
  { tag: "npc_dota_hero_treant", name: "Treant Protector" },
  { tag: "npc_dota_hero_jakiro", name: "Jakiro" },
  { tag: "npc_dota_hero_bounty_hunter", name: "Bounty Hunter" },
  { tag: "npc_dota_hero_zuus", name: "Zeus" },
  { tag: "npc_dota_hero_batrider", name: "Batrider" },
  { tag: "npc_dota_hero_tusk", name: "Tusk" },
  { tag: "npc_dota_hero_luna", name: "Luna" },
  { tag: "npc_dota_hero_magnataur", name: "Magnus" },
  { tag: "npc_dota_hero_monkey_king", name: "Monkey King" },
  { tag: "npc_dota_hero_phoenix", name: "Phoenix" },
  { tag: "npc_dota_hero_shredder", name: "Timbersaw" },
  { tag: "npc_dota_hero_rubick", name: "Rubick" },
  { tag: "npc_dota_hero_medusa", name: "Medusa" },
  { tag: "npc_dota_hero_templar_assassin", name: "Templar Assassin" },
  { tag: "npc_dota_hero_winter_wyvern", name: "Winter Wyvern" },
  { tag: "npc_dota_hero_earth_spirit", name: "Earth Spirit" },
  { tag: "npc_dota_hero_arc_warden", name: "Arc Warden" },
  { tag: "npc_dota_hero_meepo", name: "Meepo" },
  { tag: "npc_dota_hero_terrorblade", name: "Terrorblade" },
  { tag: "npc_dota_hero_visage", name: "Visage" },
  { tag: "npc_dota_hero_abyssal_underlord", name: "Underlord" },
  { tag: "npc_dota_hero_undying", name: "Undying" },
  { tag: "npc_dota_hero_wisp", name: "Io" },
  { tag: "npc_dota_hero_elder_titan", name: "Elder Titan" },
  { tag: "npc_dota_hero_phantom_assassin", name: "Phantom Assassin" },
  { tag: "npc_dota_hero_legion_commander", name: "Legion Commander" },
  { tag: "npc_dota_hero_nyx_assassin", name: "Nyx Assassin" },
  { tag: "npc_dota_hero_troll_warlord", name: "Troll Warlord" },
  { tag: "npc_dota_hero_abaddon", name: "Abaddon" },
  { tag: "npc_dota_hero_gyrocopter", name: "Gyrocopter" },
  { tag: "npc_dota_hero_disruptor", name: "Disruptor" },
  { tag: "npc_dota_hero_pangolier", name: "Pangolier" },
  { tag: "npc_dota_hero_techies", name: "Techies" },
  { tag: "npc_dota_hero_keeper_of_the_light", name: "Keeper of the Light" },
  { tag: "npc_dota_hero_skywrath_mage", name: "Skywrath Mage" },
  { tag: "npc_dota_hero_naga_siren", name: "Naga Siren" },
  { tag: "npc_dota_hero_grimstroke", name: "Grimstroke" },
  { tag: "npc_dota_hero_ember_spirit", name: "Ember Spirit" },
  { tag: "npc_dota_hero_oracle", name: "Oracle" },
  { tag: "npc_dota_hero_centaur", name: "Centaur Warrunner" },
  { tag: "npc_dota_hero_bristleback", name: "Bristleback" },
  { tag: "npc_dota_hero_slark", name: "Slark" },
  { tag: "npc_dota_hero_dark_willow", name: "Dark Willow" }
];
