name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build, Test, and Playwright
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

  docker:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build prod image
        uses: docker/build-push-action@v6.7.0
        with:
          build-args: |
            API_URL=https://dotaclassic.ru/api
            SOCKET_URL=wss://dotaclassic.ru/newsocket
            VAPID_PUBLIC_KEY=BLeadyll3oCNn_oM62pZBJzSVu2ktZwE6lciUq57Xa8aS3eAyGZ67mFgNVsDg0stn5otBlVW4HIr8E5zkFUp1u8
          push: true
          tags: dota2classic/dotabuff:prod

      - name: Build ∂ev image
        uses: docker/build-push-action@v6.7.0
        with:
          build-args: |
            API_URL=https://dev.dotaclassic.ru/api
            SOCKET_URL=wss://dev.dotaclassic.ru/newsocket
            IS_DEV_VERSION=true
            VAPID_PUBLIC_KEY=BLeadyll3oCNn_oM62pZBJzSVu2ktZwE6lciUq57Xa8aS3eAyGZ67mFgNVsDg0stn5otBlVW4HIr8E5zkFUp1u8
          push: true
          tags: dota2classic/dotabuff:dev
