name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build, Test, and Playwright
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

  docker:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    name: Build and Push Docker Image
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          build-args: |
            SENTRY_AUTH_KEY=${{ secrets.SENTRY_AUTH_KEY }}
            API_URL=https://dotaclassic.ru/api
            SOCKET_URL=wss://dotaclassic.ru/newsocket
            VAPID_PUBLIC_KEY=BLeadyll3oCNn_oM62pZBJzSVu2ktZwE6lciUq57Xa8aS3eAyGZ67mFgNVsDg0stn5otBlVW4HIr8E5zkFUp1u8
          push: true
          tags: dota2classic/dotabuff:prod

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          build-args: |
            API_URL=https://devd2c.ru/api
            SOCKET_URL=wss://devd2c.ru/newsocket
            IS_DEV_VERSION=true
            VAPID_PUBLIC_KEY=BLeadyll3oCNn_oM62pZBJzSVu2ktZwE6lciUq57Xa8aS3eAyGZ67mFgNVsDg0stn5otBlVW4HIr8E5zkFUp1u8
          push: true
          tags: dota2classic/dotabuff:dev
