name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy2
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.DEPLOY_HOST2 }}
          privateKey: ${{ secrets.DEPLOY_KEY }}
          command: cd /root/ && sh update.sh
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    needs: [ build ]
#    steps:
#      - name: executing remote ssh commands using key
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.DEPLOY_HOST }}
#          username: ${{ secrets.DEPLOY_USER }}
#          key: ${{ secrets.DEPLOY_KEY }}
#          script: cd /root/ && sh update.sh
