name: Docker Image CI

on:
#  workflow_run:
#    workflows: [ 'Playwright Tests' ]
#    types: [ completed ]
#    branches:
#      - 'master'
  push:
    branches: [ master, k8s ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          build-args: |
            VAPID_PUBLIC_KEY=BLeadyll3oCNn_oM62pZBJzSVu2ktZwE6lciUq57Xa8aS3eAyGZ67mFgNVsDg0stn5otBlVW4HIr8E5zkFUp1u8
          push: true
          tags: dota2classic/dotabuff:k8s
