name: Playwright Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    environment: Configure End2End testing
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Build app
      run: yarn build
      env:
        API_URL: ${{ env.API_URL }}
    - name: Run Playwright tests
      run: yarn playwright test
      env:
        PLAYWRIGHT_NEWBIE_USER: ${{ secrets.PLAYWRIGHT_NEWBIE_USER }}
        PLAYWRIGHT_NEWBIE_USER_ID: ${{ env.PLAYWRIGHT_NEWBIE_USER_ID }}
        PLAYWRIGHT_NEWBIE_USER_NAME: ${{ env.PLAYWRIGHT_NEWBIE_USER_NAME }}
        FAKE_SECRET: ${{ secrets.FAKE_SECRET }}
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
